import type { EndgameDrill } from '../types';

// Endgame drills, played out against Stockfish. The learner plays the side to move.
export const drills: EndgameDrill[] = [
  // ---------------------------------------------------------------- Basic mates
  {
    id: "eg-kqk-centre",
    title: "Queen mate: king in the centre",
    category: "Basic mates",
    level: "Beginner",
    fen: "8/8/8/3k4/8/8/8/Q3K3 w - - 0 1",
    goal: "win",
    maxMoves: 15,
    brief: "Checkmate the lone king with king and queen within 15 moves.",
    tips: [
      "Shrink the box: put the queen a knight's move away from the enemy king and follow it, so its area gets smaller every move.",
      "Quiet queen moves that take squares away are faster than checks, which usually just chase the king around.",
      "Once the king is stuck on the edge, stop moving the queen and bring your own king up.",
      "Before every quiet queen move, make sure the black king still has a legal move: stalemate is the only way to spoil this.",
    ],
  },
  {
    id: "eg-kqk-far-king",
    title: "Queen mate: king starts far away",
    category: "Basic mates",
    level: "Beginner",
    fen: "7Q/8/8/8/4k3/8/8/K7 w - - 0 1",
    goal: "win",
    maxMoves: 15,
    brief: "Your king starts in the corner. Restrict the black king with the queen, walk your king over and mate within 15 moves.",
    tips: [
      "The queen alone can build the box: a knight's move away from the king takes the most squares without giving check.",
      "While the queen keeps the box closed, march your king toward the enemy king every move.",
      "Mating patterns: the queen right in front of the enemy king protected by your king, or the queen along the edge with your king facing the enemy king.",
      "Check for stalemate after each quiet move, especially when the king is in a corner.",
    ],
  },
  {
    id: "eg-kqk-stalemate-trap",
    title: "Queen mate: don't stalemate",
    category: "Basic mates",
    level: "Beginner",
    fen: "k7/8/8/8/8/8/1Q6/6K1 w - - 0 1",
    goal: "win",
    maxMoves: 10,
    brief: "The black king is already caged in the corner. Bring your king over and mate within 10 moves without giving stalemate.",
    tips: [
      "The queen on b2 already keeps the king on a7 and a8. Leave it there.",
      "Do not take away the last free square: 1.Qb6?? is stalemate at once.",
      "Walk your king to c7 or b6; then the queen mates on b7, a7 or b8.",
    ],
  },
  {
    id: "eg-krk-centre",
    title: "Rook mate: from the centre",
    category: "Basic mates",
    level: "Beginner",
    fen: "8/8/8/4k3/8/8/8/R3K3 w - - 0 1",
    goal: "win",
    maxMoves: 25,
    brief: "Checkmate with king and rook within 25 moves.",
    tips: [
      "Cut the king off with the rook along a rank or file, then shrink the box one line at a time.",
      "Your king does the pushing: bring it in front of the enemy king so they face each other with one square between (opposition), then check with the rook.",
      "If the black king attacks your rook, move the rook far away along the same line, keeping the cut.",
      "When you need Black to step into opposition, make a waiting move with the rook along its line.",
    ],
  },
  {
    id: "eg-krk-edge",
    title: "Rook mate: king on the back rank",
    category: "Basic mates",
    level: "Beginner",
    fen: "4k3/8/8/8/8/8/8/R5K1 w - - 0 1",
    goal: "win",
    maxMoves: 20,
    brief: "The black king is already on the back rank. Keep it there and mate within 20 moves.",
    tips: [
      "Put the rook on the seventh rank: the king is locked on the eighth.",
      "March your king up the board; the rook only moves when it is attacked or when you need a waiting move.",
      "Mate comes when the kings face each other on the same file and the rook checks along the eighth rank.",
      "If the black king runs away from your king, follow it; a spare rook move along the seventh rank forces it into opposition.",
    ],
  },
  {
    id: "eg-two-rooks-ladder",
    title: "Two rooks: the ladder mate",
    category: "Basic mates",
    level: "Beginner",
    fen: "8/8/8/3k4/8/8/8/R3K2R w - - 0 1",
    goal: "win",
    maxMoves: 10,
    brief: "Mate with the two rooks within 10 moves. Your king is not needed.",
    tips: [
      "One rook cuts the king off along a rank, the other checks on the next rank: they leapfrog up the board like a ladder.",
      "The rooks work on neighbouring ranks (or files) so the king can never step between them.",
      "If the king comes close to a rook, swing that rook to the far side of the board on the same rank before continuing.",
    ],
  },
  {
    id: "eg-two-bishops",
    title: "Two bishops mate",
    category: "Basic mates",
    level: "Intermediate",
    fen: "4k3/8/3K4/8/8/8/8/2B2B2 w - - 0 1",
    goal: "win",
    maxMoves: 25,
    brief: "The black king is on the back rank. Keep it there, drive it into a corner and mate with the two bishops within 25 moves.",
    tips: [
      "Place the bishops next to each other on neighbouring diagonals: together they form a wall the king cannot cross.",
      "Your king must join in: it takes squares from the enemy king and protects the bishops.",
      "Mate is only possible in a corner, so push the king along the edge toward the nearest one.",
      "Final pattern: the king in the corner, one bishop checks while the other bishop and your king cover the escape squares. Watch out for stalemate.",
    ],
  },
  {
    id: "eg-bishop-knight",
    title: "Bishop and knight mate",
    category: "Basic mates",
    level: "Advanced",
    fen: "3k4/8/3K4/8/8/8/8/4NB2 w - - 0 1",
    goal: "win",
    maxMoves: 40,
    brief: "Mate with bishop and knight within 40 moves. Mate only works in a corner of the bishop's colour: a8 or h1 for your light-squared bishop.",
    tips: [
      "The target corner is a8. Keep the black king on the eighth rank and push it toward the queenside.",
      "Your king stays close, two squares away from the enemy king; the bishop takes the light squares, the knight the dark ones.",
      "If the king runs toward the wrong (dark) corner h8, use the W-manoeuvre: the knight walks along a zig-zag (e.g. f7-e5-d7-c5) while the bishop covers the light squares, herding the king along the edge.",
      "Set up the net before checking: random checks let the king escape to the centre.",
      "Final phase: the king shuttles between a8, b8 and a7; the bishop gives the last check on the long diagonal or on the edge with the knight covering the dark escape square.",
    ],
  },

  // ---------------------------------------------------------------- Pawn endgames
  {
    id: "eg-kpk-spare-tempo",
    title: "King and pawn: the spare tempo",
    category: "Pawn endgames",
    level: "Beginner",
    fen: "8/8/4k3/8/4K3/8/4P3/8 w - - 0 1",
    goal: "promote",
    maxMoves: 15,
    brief: "The kings face each other. Use the opposition, and your spare pawn move if needed, to escort the e-pawn to promotion.",
    tips: [
      "Your king is in front of the pawn: that is the winning set-up. Let the king lead and the pawn follow.",
      "Opposition: kings on the same file with one square between. The side that does NOT have to move has it. A pawn move like 1.e3 hands the move to Black.",
      "Key squares: for a pawn on its 2nd to 4th rank, the three squares two ranks in front of it (for e2: d4, e4, f4; for e4: d6, e6, f6). A king on a key square wins by force, so keep your king on one as the pawn advances.",
      "Don't push the pawn early: a pawn close to your king is safe, and the spare tempo may be needed later.",
    ],
  },
  {
    id: "eg-kpk-defend",
    title: "King and pawn: defend the draw",
    category: "Pawn endgames",
    level: "Beginner",
    fen: "4k3/8/8/4P3/4K3/8/8/8 b - - 0 1",
    goal: "draw",
    maxMoves: 20,
    brief: "Black to move. Hold the draw against king and pawn by keeping your king in front of the pawn.",
    tips: [
      "Stay on the pawn's file or right next to it, always in front of the pawn.",
      "Take the opposition whenever the white king steps forward: if it comes to d5, answer ...Kd7; to f5, answer ...Kf7.",
      "When the pawn advances with check, step straight back toward the promotion square (e8), never to the side.",
      "In the end White can only stalemate you or give up the pawn.",
    ],
  },
  {
    id: "eg-rule-of-the-square",
    title: "The rule of the square",
    category: "Pawn endgames",
    level: "Beginner",
    fen: "k7/8/8/8/p5P1/4K3/8/8 w - - 0 1",
    goal: "promote",
    maxMoves: 12,
    brief: "White to move. Black's a-pawn wins the race against your g-pawn, so catch it with your king first, then promote your own pawn.",
    tips: [
      "Draw the square of the a4 pawn: a4-d4-d1-a1. If your king can step into it, it catches the pawn.",
      "1.Kd2, 1.Kd3 or 1.Kd4 steps into the square. 1.g5? a3 lets both sides promote with a drawn queen ending.",
      "After you win the a-pawn, count again: the black king on a8 is far outside the square of your g-pawn.",
    ],
  },
  {
    id: "eg-outside-passed-pawn",
    title: "The outside passed pawn",
    category: "Pawn endgames",
    level: "Intermediate",
    fen: "8/8/3k2p1/7p/P2K3P/6P1/8/8 w - - 0 1",
    goal: "promote",
    maxMoves: 20,
    brief: "White to move. Use your a-pawn as a decoy to pull the black king away, then win the kingside pawns and promote.",
    tips: [
      "The a-pawn is far from the other pawns. Push it, and the black king has to run after it.",
      "While the black king chases the a-pawn, your king marches to the kingside and eats g6 and h5.",
      "The a-pawn's job is to deflect the king, so sacrificing it is fine if your king is already on its way to the other pawns.",
    ],
  },
  {
    id: "eg-pawn-breakthrough",
    title: "Pawn breakthrough",
    category: "Pawn endgames",
    level: "Intermediate",
    fen: "7k/ppp5/8/PPP5/8/8/8/7K w - - 0 1",
    goal: "promote",
    maxMoves: 8,
    brief: "White to move. Three pawns face three pawns and the kings are far away. Break through and promote a pawn.",
    tips: [
      "The key is 1.b6!, attacking a7 and c7 at once.",
      "If 1...axb6, then 2.c6! bxc6 3.a6 and the a-pawn runs through. If 1...cxb6, then 2.a6! bxa6 3.c6.",
      "Count before you start: the black king on h8 is too far away to stop a pawn on the a- or c-file.",
    ],
  },
  {
    id: "eg-lose-a-tempo",
    title: "Zugzwang: lose a tempo with the king",
    category: "Pawn endgames",
    level: "Advanced",
    fen: "8/8/2p5/2Pk4/3P4/3K4/8/8 w - - 0 1",
    goal: "promote",
    maxMoves: 20,
    brief: "White to move. If it were Black's move, Black would be in zugzwang and lose. Hand the move over with a king manoeuvre, then break through.",
    tips: [
      "The black king on d5 has almost no moves: d6 and e5 are covered by your pawns and d4 is protected. Every king move gives up something.",
      "Your king has more room than Black's, so it can lose a move: 1.Ke3! keeps d4 protected and passes the move. 1.Kd2? or 1.Ke2? allows ...Kxd4, and 1.Kc3? Ke6 lets Black hold the e5 entry square.",
      "After 1...Ke6, take the opposition with 2.Ke4 and break through with d4-d5. After 1...Kc4, 2.Ke4! and your king reaches c6 before Black's king can do damage.",
      "This is the idea behind triangulation: when the enemy king can only shuffle between two squares, walk a three-square route to reach the same position with the opponent to move."
    ],
  },

  // ---------------------------------------------------------------- Rook endgames
  {
    id: "eg-lucena",
    title: "Lucena position: build a bridge",
    category: "Rook endgames",
    level: "Intermediate",
    fen: "1K6/1P1k4/8/8/8/8/r7/2R5 w - - 0 1",
    goal: "promote",
    maxMoves: 15,
    brief: "White to move. This is the Lucena position: free your king from b8 and promote the pawn.",
    tips: [
      "First push the black king one more file away with a check: 1.Rd1+.",
      "Then put your rook on the fourth rank (Rd4): this is the bridge.",
      "Walk the king out (Kc7, Kb6, Kc6, Kb5) and when the black rook runs out of checks, block the last check with the rook on b4.",
      "Keep your rook between the black king and your pawn so the king can never come back.",
    ],
  },
  {
    id: "eg-philidor",
    title: "Philidor position: third-rank defence",
    category: "Rook endgames",
    level: "Intermediate",
    fen: "4k3/R7/7r/3KP3/8/8/8/8 b - - 0 1",
    goal: "draw",
    maxMoves: 30,
    brief: "Black to move. Hold the draw with rook against rook and pawn using Philidor's method.",
    tips: [
      "Keep your rook on the sixth rank (your third rank) so the white king cannot advance to d6, e6 or f6.",
      "Keep your king on the promotion square or right next to it.",
      "As soon as the pawn steps to e6, swing the rook to the first rank (...Rh1) and check the white king from behind: it has no shelter any more.",
      "Don't let your rook go passive on the back rank while the pawn is still on the fifth.",
    ],
  },
  {
    id: "eg-rook-cut-off",
    title: "Cut the king off",
    category: "Rook endgames",
    level: "Advanced",
    fen: "7r/8/6k1/8/3P4/3K4/8/4R3 w - - 0 1",
    goal: "promote",
    maxMoves: 30,
    brief: "White to move. Your rook on the e-file cuts the black king off from the d-pawn. Escort the pawn to promotion.",
    tips: [
      "Keep the rook on the e-file as long as possible: it keeps the black king away from the pawn.",
      "Advance king and pawn together. The king walks in front of the pawn and shields it from checks.",
      "When the black rook checks from the side, walk toward it or block with the rook; checks from behind are harmless if your king stays in front.",
      "The goal is a Lucena position: pawn on the seventh, king on the promotion square, then build the bridge with the rook.",
    ],
  },
  {
    id: "eg-rook-vs-pawn-win",
    title: "Rook against pawn: win it",
    category: "Rook endgames",
    level: "Intermediate",
    fen: "8/8/8/8/2pk4/8/4K3/1R6 w - - 0 1",
    goal: "win",
    maxMoves: 35,
    brief: "White to move. Stop the c-pawn, win it, then checkmate with king and rook within 35 moves.",
    tips: [
      "Get your king in front of the pawn as fast as possible: 1.Kd2 takes key squares away from the black king.",
      "Use the rook to cut the black king off from its pawn along a rank or file.",
      "The rook alone can't stop a pawn that its king supports; your king must arrive in time.",
      "Once the pawn falls, finish with the standard rook mate: box the king in and use the opposition.",
    ],
  },
  {
    id: "eg-rook-vs-pawn-draw",
    title: "Rook against pawn: hold the draw",
    category: "Rook endgames",
    level: "Intermediate",
    fen: "8/6K1/8/8/2p5/2k5/8/R7 b - - 0 1",
    goal: "draw",
    maxMoves: 20,
    brief: "Black to move. The white king is far away. Push the c-pawn with your king right beside it and force White to give up the rook.",
    tips: [
      "Keep your king next to the pawn: 1...Kb2 attacks the rook and supports the pawn at the same time.",
      "Push the pawn only when your king protects it; an unprotected pawn is simply picked up by the rook.",
      "If the rook takes the new queen, king against king is a draw by insufficient material.",
    ],
  },

  // ---------------------------------------------------------------- Minor pieces
  {
    id: "eg-wrong-bishop",
    title: "Wrong bishop and rook pawn",
    category: "Minor pieces",
    level: "Intermediate",
    fen: "8/4k3/8/7P/2B2K2/8/8/8 b - - 0 1",
    goal: "draw",
    maxMoves: 25,
    brief: "Black to move. White's bishop is light-squared, but h8 is a dark square. Reach the corner and the game is a draw.",
    tips: [
      "Head for the corner at once: ...Kf6, ...Kg7 and ...Kh8.",
      "A light-squared bishop can never attack h8, and the h-pawn cannot drive your king out: it is a fortress.",
      "Don't wander toward the centre: if the white king takes g7 and h7 away first, the pawn promotes.",
      "Once in the corner, shuffle between the free corner squares. White can only stalemate you or give up the pawn.",
    ],
  },
  {
    id: "eg-knight-vs-pawn",
    title: "Knight against pawn",
    category: "Minor pieces",
    level: "Intermediate",
    fen: "7K/8/8/8/8/1p6/2k5/3N4 w - - 0 1",
    goal: "draw",
    maxMoves: 20,
    brief: "White to move. Your king is far away, so the knight must stop the b-pawn alone. Find the only move, then keep the pawn from promoting.",
    tips: [
      "1.Ne3+! gains a tempo with check; a quiet move lets the pawn run to b1.",
      "The knight wants to control b1 and b2: from d1, c3, a3 and d2 it covers the promotion square.",
      "Use checks to drive the king away whenever it shelters the pawn, then return to a guarding square.",
      "Knight against pawn is usually a draw; the dangerous case is a rook pawn on the seventh rank supported by its king.",
    ],
  },

  // ---------------------------------------------------------------- Queen endgames
  {
    id: "eg-queen-vs-centre-pawn",
    title: "Queen against a centre pawn",
    category: "Queen endgames",
    level: "Advanced",
    fen: "K7/8/8/8/8/8/3pk3/6Q1 w - - 0 1",
    goal: "win",
    maxMoves: 30,
    brief: "White to move. Black's d-pawn is one step from queening and your king is far away. Stop it, win it and mate within 30 moves.",
    tips: [
      "Check and pin until the black king has to step in front of its own pawn (to d1).",
      "Each time the king blocks the pawn, Black loses a tempo: use it to bring your king one step closer.",
      "Repeat the cycle (checks, king forced to d1, one king move) until your king helps win the pawn, then mate.",
      "This works against a centre or knight pawn. Against a bishop or rook pawn the defender has stalemate tricks.",
    ],
  },
  {
    id: "eg-queen-vs-bishop-pawn",
    title: "Queen against a bishop pawn: stalemate defence",
    category: "Queen endgames",
    level: "Advanced",
    fen: "6K1/8/8/8/8/8/2pk1Q2/8 b - - 0 1",
    goal: "draw",
    maxMoves: 25,
    brief: "Black to move and in check. With a c-pawn on the seventh rank and the white king far away, you can hold the draw.",
    tips: [
      "Keep the pawn protected and head for the queenside corner: b1, b2 and a1.",
      "The trick: with your king on a1, Qxc2 is stalemate, so White can never take the pawn there.",
      "Avoid the d-file side of the pawn: from there the stalemate trick does not exist and White gains the tempi to bring the king.",
    ],
  },
  {
    id: "eg-queen-vs-rook-pawn",
    title: "Queen against a rook pawn",
    category: "Queen endgames",
    level: "Advanced",
    fen: "6K1/8/8/8/8/8/p1k5/5Q2 b - - 0 1",
    goal: "draw",
    maxMoves: 25,
    brief: "Black to move. Your a-pawn is on the seventh rank; keep your king next to it and White cannot make progress.",
    tips: [
      "Play 1...Kb2 at once to protect the pawn; if the king drifts away, the queen picks up the pawn.",
      "If you are driven into the corner on a1, any quiet queen move that covers your last square is stalemate.",
      "Stay on b1, b2 or a1: without help from the white king, the queen alone cannot win the pawn.",
    ],
  },
];
