import type { Opening } from '../types';

// Black repertoire: 1...e5 or the Caro-Kann / Sicilian Najdorf against 1.e4,
// the Queen's Gambit Declined or the King's Indian against 1.d4.
export const blackOpenings: Opening[] = [
  {
    id: "b-e4-e5",
    name: "Open Game: 1.e4 e5",
    eco: "C20",
    side: "black",
    level: "Beginner",
    summary:
      "Answering 1.e4 with 1...e5 is the classical, principled choice: Black claims an equal share of the centre and develops naturally. This chapter shows how to meet the three most popular White systems, the Italian, the Ruy Lopez and the Scotch, with sound mainstream lines.",
    ideas: [
      "Fight for the centre with ...e5, ...Nc6 and ...d6, and never give up the e5 point without a reason.",
      "Against the slow Italian, mirror White's set-up (...a6, ...Ba7, ...h6, ...Re8) and trade the Italian bishop with ...Be6.",
      "In the Two Knights, meet 4.Ng5 d5 5.exd5 with 5...Na5: never 5...Nxd5, which invites the Fried Liver attack.",
      "In the Ruy Lopez, gain queenside space with ...a6 and ...b5, then regroup with the Breyer knight ...Nb8-d7 to hold e5.",
      "Against the Scotch, develop with ...Bc5 and use the queen from f6 to put quick pressure on d4 and f2.",
    ],
    lines: [
      {
        id: "b-e5-italian-pianissimo",
        name: "Italian: 3...Bc5 4.c3 Nf6 5.d3 d6",
        moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O a6 a4 Ba7 Re1 O-O h3 h6 Nbd2 Re8 Nf1 Be6 Bxe6 Rxe6",
        notes: {
          1: "White takes the centre.",
          2: "1...e5 claims an equal share of the centre and frees the f8 bishop.",
          3: "White develops with a threat to e5.",
          4: "2...Nc6 defends e5 and develops.",
          5: "3.Bc4, the Italian Game, aims at f7.",
          6: "3...Bc5 develops the bishop to its most active square, eyeing f2.",
          7: "4.c3 prepares d4.",
          8: "4...Nf6 attacks e4 and prepares castling.",
          9: "5.d3 is the quiet Giuoco Pianissimo.",
          10: "5...d6 supports e5 and frees the c8 bishop.",
          11: "White castles.",
          12: "6...a6 prepares ...Ba7, keeping the bishop safe from b4 or d4 with tempo.",
          13: "7.a4 stops ...b5.",
          14: "7...Ba7: the bishop stays on the a7-g1 diagonal, still pointing at f2.",
          15: "White supports e4 and prepares Nbd2-f1.",
          16: "8...O-O: king safety first.",
          17: "9.h3 keeps our pieces out of g4.",
          18: "9...h6 keeps White's pieces out of g5.",
          19: "White starts the knight tour d2-f1-g3.",
          20: "10...Re8 supports e5 and prepares ...Be6.",
          21: "11.Nf1 heads for g3.",
          22: "11...Be6 offers to trade White's strong Italian bishop.",
          23: "12.Bxe6 accepts the trade.",
          24: "12...Rxe6 keeps the pawn structure healthy; the rook can later swing along the sixth rank. Black plans ...d5 to equalise completely.",
        },
      },
      {
        id: "b-e5-two-knights-ng5",
        name: "Two Knights: 3...Nf6 4.Ng5 d5 5.exd5 Na5",
        moves: "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Be2 h6 Nf3 e4 Ne5 Bd6 d4 exd3 Nxd3 Qc7",
        notes: {
          2: "1...e5 takes our share of the centre.",
          4: "2...Nc6 defends e5.",
          5: "3.Bc4, the Italian bishop.",
          6: "3...Nf6, the Two Knights Defence, counterattacks e4 immediately.",
          7: "4.Ng5 attacks f7 twice.",
          8: "4...d5! blocks the bishop's diagonal toward f7.",
          9: "5.exd5 takes the pawn.",
          10: "5...Na5! attacks the bishop. Never 5...Nxd5?, which allows the Fried Liver attack 6.Nxf7 or 6.d4.",
          11: "6.Bb5+ keeps the bishop active.",
          12: "6...c6 blocks the check and offers a pawn to gain time.",
          13: "7.dxc6 accepts.",
          14: "7...bxc6: Black is a pawn down but ahead in development, with open lines.",
          15: "8.Be2 is the main retreat.",
          16: "8...h6 kicks the knight away from g5.",
          17: "9.Nf3.",
          18: "9...e4 gains space and hits the knight again.",
          19: "10.Ne5.",
          20: "10...Bd6 develops with pressure on the e5 knight.",
          21: "11.d4 supports the knight.",
          22: "11...exd3 captures en passant to open lines against the white king.",
          23: "12.Nxd3.",
          24: "12...Qc7 hits h2 and prepares to castle. Black has excellent compensation for the pawn: quick development, the bishop pair and attacking chances.",
        },
      },
      {
        id: "b-e5-ruy-breyer",
        name: "Ruy Lopez: Morphy Defence, Breyer Variation",
        moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8",
        notes: {
          2: "1...e5 takes our share of the centre.",
          4: "2...Nc6 defends e5.",
          5: "3.Bb5, the Ruy Lopez, pressures the defender of e5.",
          6: "3...a6, the Morphy Defence, questions the bishop at once.",
          7: "4.Ba4 keeps the pressure.",
          8: "4...Nf6 develops and attacks e4.",
          9: "5.O-O.",
          10: "5...Be7 prepares to castle: the solid Closed Ruy Lopez.",
          11: "6.Re1 defends e4 and now threatens Bxc6 and Nxe5.",
          12: "6...b5 drives the bishop away and removes the threat.",
          13: "7.Bb3.",
          14: "7...d6 supports e5 and opens the c8 bishop.",
          15: "8.c3 prepares d4.",
          16: "8...O-O: king safety first; now Black is ready to regroup.",
          17: "9.h3 prepares d4 without allowing ...Bg4.",
          18: "9...Nb8! The Breyer: the knight reroutes to d7, where it supports e5 and frees the c-pawn.",
          19: "10.d4.",
          20: "10...Nbd7 completes the manoeuvre.",
          21: "11.Nbd2.",
          22: "11...Bb7 puts pressure on e4.",
          23: "12.Bc2.",
          24: "12...Re8 prepares ...Bf8 and ...g6 with ...Bg7, a rock-solid set-up. Later Black plays ...c5 or ...c6 to fight in the centre.",
        },
      },
      {
        id: "b-e5-scotch-be3",
        name: "Scotch: 4...Bc5 5.Be3 Qf6",
        moves: "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Be3 Qf6 c3 Nge7 Bc4 Ne5 Be2 Qg6 O-O d6",
        notes: {
          2: "1...e5 takes our share of the centre.",
          4: "2...Nc6 defends e5.",
          5: "3.d4, the Scotch, opens the centre immediately.",
          6: "3...exd4: we cannot hold e5, so we take.",
          7: "4.Nxd4 recaptures.",
          8: "4...Bc5 develops with an attack on the centralised knight.",
          9: "5.Be3 defends the knight.",
          10: "5...Qf6 adds pressure on d4, threatening ...Nxd4.",
          11: "6.c3 supports d4 again.",
          12: "6...Nge7 develops; on e7 the knight does not block the queen.",
          13: "7.Bc4 aims at f7.",
          14: "7...Ne5 hits the bishop and centralises the knight.",
          15: "8.Be2.",
          16: "8...Qg6 turns the queen against e4 and g2.",
          17: "9.O-O.",
          18: "9...d6 supports the e5 knight and opens the c8 bishop, preparing ...Bh3 or ...O-O. Black's pieces are active and the game is balanced.",
        },
      },
      {
        id: "b-e5-scotch-nxc6",
        name: "Scotch: 4...Bc5 5.Nxc6 Qf6",
        moves: "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Nxc6 Qf6 Qd2 dxc6 Nc3 Be6 Na4 Bd6",
        notes: {
          2: "1...e5 takes our share of the centre.",
          4: "2...Nc6 defends e5.",
          5: "3.d4, the Scotch.",
          6: "3...exd4: e5 cannot be held, so we take and develop quickly.",
          7: "4.Nxd4.",
          8: "4...Bc5 attacks the knight.",
          9: "5.Nxc6 trades knights before we can pressure d4.",
          10: "5...Qf6! threatens mate on f2 and attacks the c6 knight, so White has no time to keep the extra piece.",
          11: "6.Qd2 defends f2 (6.Qf3 is also played).",
          12: "6...dxc6 recaptures toward the centre, opening the d-file and the c8 bishop.",
          13: "7.Nc3.",
          14: "7...Be6 develops, preparing to castle queenside.",
          15: "8.Na4 hits our bishop.",
          16: "8...Bd6 keeps the bishop on a good diagonal. Black plans ...Ne7 and ...O-O-O with active pieces; the doubled c-pawns hardly matter.",
        },
      },
    ],
  },
  {
    id: "b-caro-kann",
    name: "Caro-Kann Defence",
    eco: "B12",
    side: "black",
    level: "Beginner",
    summary:
      "The Caro-Kann (1...c6 and 2...d5) is one of the most reliable answers to 1.e4. Black builds a solid pawn structure, develops the light-squared bishop outside the pawn chain and aims for a healthy position with few weaknesses and good endgames.",
    ideas: [
      "Challenge e4 with ...d5 supported by ...c6, and develop the c8 bishop to f5 or g4 before playing ...e6.",
      "In the Classical, meet h4-h5 by giving the bishop room (...h6, ...Bh7), trade it, then play ...e6, ...Ngf6, ...Be7 and castle.",
      "Against the Advance, hit the pawn chain with ...c5 and pressure d4 with ...Nc6 and ...Qb6 or ...Ne7-c6.",
      "In the Exchange structure, use the half-open c-file for a minority attack with ...b5-b4.",
      "Against the Panov's isolated d4 pawn, blockade d5 with a knight and trade pieces.",
    ],
    lines: [
      {
        id: "b-caro-classical",
        name: "Classical: 3.Nc3 dxe4 4.Nxe4 Bf5",
        moves: "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7 Bd3 Bxd3 Qxd3 e6 Bd2 Ngf6 O-O-O Be7",
        notes: {
          2: "1...c6 prepares ...d5 while keeping the c8 bishop's diagonal open.",
          4: "2...d5 challenges e4.",
          5: "3.Nc3 defends e4.",
          6: "3...dxe4 exchanges in the centre.",
          7: "4.Nxe4.",
          8: "4...Bf5 develops the bishop with tempo on the knight: the Classical Variation.",
          9: "5.Ng3 attacks the bishop.",
          10: "5...Bg6 keeps the bishop on the key diagonal.",
          11: "6.h4 threatens h5 to trap or chase the bishop.",
          12: "6...h6 gives the bishop an escape square on h7.",
          13: "7.Nf3.",
          14: "7...Nd7 stops Ne5 hitting the bishop.",
          15: "8.h5 gains space.",
          16: "8...Bh7 retreats to safety.",
          17: "9.Bd3 offers to trade bishops.",
          18: "9...Bxd3 accepts; our bishop has done its job.",
          19: "10.Qxd3.",
          20: "10...e6 opens the f8 bishop.",
          21: "11.Bd2.",
          22: "11...Ngf6 develops and prepares to castle.",
          23: "12.O-O-O: White castles long.",
          24: "12...Be7 prepares to castle. Black is solid and will look for ...c5 or ...Qa5 counterplay; the h5 pawn can become a target in the endgame.",
        },
      },
      {
        id: "b-caro-advance",
        name: "Advance: 3.e5 Bf5 4.Nf3 e6 5.Be2 c5",
        moves: "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 cxd4 Nxd4 Ne7 c4 Nbc6 Qa4 dxc4 Nc3 a6",
        notes: {
          2: "1...c6, the Caro-Kann, prepares ...d5 without blocking the c8 bishop.",
          4: "2...d5 challenges e4.",
          5: "3.e5 is the Advance Variation.",
          6: "3...Bf5 develops the bishop outside the pawn chain before ...e6.",
          7: "4.Nf3, the Short System.",
          8: "4...e6 opens the f8 bishop.",
          9: "5.Be2.",
          10: "5...c5 attacks the base of the pawn chain.",
          11: "6.Be3 defends d4.",
          12: "6...cxd4 opens the c-file.",
          13: "7.Nxd4.",
          14: "7...Ne7 heads for c6 to hit the d4 knight.",
          15: "8.c4 attacks our centre.",
          16: "8...Nbc6 challenges the d4 knight.",
          17: "9.Qa4 pins the c6 knight.",
          18: "9...dxc4 grabs a pawn and opens the d-file.",
          19: "10.Nc3.",
          20: "10...a6 prepares ...b5 to break the pin and secure the extra pawn. The position is sharp: Black follows up with ...Qc7 or ...Bd3 and quick development.",
        },
      },
      {
        id: "b-caro-exchange",
        name: "Exchange: 3.exd5 cxd5 4.Bd3",
        moves: "e4 c6 d4 d5 exd5 cxd5 Bd3 Nc6 c3 Nf6 Bf4 Bg4 Qb3 Qd7 Nd2 e6 Ngf3 Bxf3 Nxf3 Bd6 Bxd6 Qxd6 O-O O-O",
        notes: {
          2: "1...c6, the Caro-Kann, prepares ...d5 without blocking the c8 bishop.",
          4: "2...d5 challenges e4.",
          5: "3.exd5, the Exchange Variation.",
          6: "3...cxd5: a symmetrical structure, but Black has the half-open c-file.",
          7: "4.Bd3.",
          8: "4...Nc6 develops and eyes d4.",
          9: "5.c3.",
          10: "5...Nf6 develops and controls e4.",
          11: "6.Bf4.",
          12: "6...Bg4 develops the bishop actively before ...e6 shuts it in.",
          13: "7.Qb3 attacks b7.",
          14: "7...Qd7 simply defends b7.",
          15: "8.Nd2.",
          16: "8...e6 opens the f8 bishop.",
          17: "9.Ngf3.",
          18: "9...Bxf3 removes a knight that could jump to e5.",
          19: "10.Nxf3.",
          20: "10...Bd6 offers to trade White's active bishop.",
          21: "11.Bxd6.",
          22: "11...Qxd6 recaptures; the queen is well placed, eyeing h2 and the queenside.",
          23: "12.O-O.",
          24: "12...O-O. Black plans a minority attack with ...Rab8 and ...b5-b4 to create weaknesses in White's queenside.",
        },
      },
      {
        id: "b-caro-panov",
        name: "Panov Attack: 4.c4 Nf6 5.Nc3 e6",
        moves: "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Be7 cxd5 Nxd5 Bd3 Nc6 O-O O-O Re1 Bf6 Be4 Nce7",
        notes: {
          2: "1...c6, the Caro-Kann, prepares ...d5 without blocking the c8 bishop.",
          4: "2...d5 challenges e4.",
          5: "3.exd5.",
          6: "3...cxd5 recaptures toward the centre.",
          7: "4.c4, the Panov, aims for an isolated queen's pawn position.",
          8: "4...Nf6 develops and pressures d5.",
          9: "5.Nc3.",
          10: "5...e6 supports d5 and opens the bishop.",
          11: "6.Nf3.",
          12: "6...Be7 prepares to castle.",
          13: "7.cxd5.",
          14: "7...Nxd5 recaptures with the knight: d5 is the ideal blockade square.",
          15: "8.Bd3.",
          16: "8...Nc6 pressures the isolated d4 pawn.",
          17: "9.O-O.",
          18: "9...O-O: king safety before the fight for d4 begins.",
          19: "10.Re1.",
          20: "10...Bf6 adds pressure on d4.",
          21: "11.Be4.",
          22: "11...Nce7 reinforces d5, so the blockade holds. Black plans ...b6, ...Bb7 and ...Rc8: trade pieces and the isolated pawn becomes a weakness.",
        },
      },
    ],
  },
  {
    id: "b-sicilian",
    name: "Sicilian Defence: Najdorf",
    eco: "B90",
    side: "black",
    level: "Advanced",
    summary:
      "The Sicilian (1...c5) fights for the centre asymmetrically and is Black's most ambitious answer to 1.e4. In the Najdorf (5...a6) Black keeps options open: ...e5 or ...e6, ...b5 queenside expansion and counterplay on the c-file. Against the Alapin (2.c3) Black gets free, comfortable piece play.",
    ideas: [
      "After ...cxd4 Black has an extra central pawn and the half-open c-file.",
      "5...a6 takes b5 away from White's pieces, prepares ...b5 and keeps ...e5 available.",
      "When White castles long, race on the queenside: ...b5-b4, ...Nbd7-b6 or -c5 and ...Rc8. Speed beats material.",
      "With ...e5, the d5 square is the key: control it with ...Be6 and ...Nbd7-f6 or -b6, and prepare the ...d5 break.",
      "Against 2.c3, play 2...Nf6 and meet e5 with ...Nd5, then attack the centre with ...Nc6, ...d6 and ...e6.",
    ],
    lines: [
      {
        id: "b-sic-najdorf-english",
        name: "Najdorf: 6.Be3 e5, the English Attack",
        moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O O-O-O Nbd7 g4 b5",
        notes: {
          2: "1...c5, the Sicilian, fights for d4 from the side and creates an unbalanced game.",
          4: "2...d6 prepares ...Nf6 and controls e5.",
          5: "3.d4 opens the centre.",
          6: "3...cxd4 trades a wing pawn for a centre pawn.",
          7: "4.Nxd4.",
          8: "4...Nf6 hits e4 and forces Nc3.",
          9: "5.Nc3.",
          10: "5...a6 is the Najdorf: it takes b5 from White's knights and prepares ...b5 or ...e5.",
          11: "6.Be3 prepares f3, Qd2 and O-O-O: the English Attack.",
          12: "6...e5 kicks the knight and claims central space.",
          13: "7.Nb3.",
          14: "7...Be6 controls d5.",
          15: "8.f3 supports e4 and prepares g4.",
          16: "8...Be7 develops and prepares castling.",
          17: "9.Qd2.",
          18: "9...O-O: we castle short; White's king will go the other way.",
          19: "10.O-O-O: opposite-side castling means a race.",
          20: "10...Nbd7 prepares ...b5 and ...Nb6.",
          21: "11.g4 starts the kingside storm.",
          22: "11...b5! starts our counterattack; ...b4 will kick the c3 knight. In these races speed matters more than material.",
        },
      },
      {
        id: "b-sic-najdorf-bg5",
        name: "Najdorf: 6.Bg5 e6",
        moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4 Be7 Qf3 Qc7 O-O-O Nbd7 g4 b5 Bxf6 Nxf6 g5 Nd7",
        notes: {
          2: "1...c5, the Sicilian, fights for d4 from the side and creates an unbalanced game.",
          4: "2...d6 prepares ...Nf6 and controls e5.",
          6: "3...cxd4 trades a wing pawn for a centre pawn.",
          8: "4...Nf6 attacks e4.",
          10: "5...a6, the Najdorf, takes b5 from White's pieces and prepares ...e5 or ...e6.",
          11: "6.Bg5 pins the knight and prepares f4.",
          12: "6...e6 is the most solid reply; the pin will be broken with ...Be7.",
          13: "7.f4 prepares e5.",
          14: "7...Be7 breaks the pin.",
          15: "8.Qf3.",
          16: "8...Qc7 controls e5 and the c-file.",
          17: "9.O-O-O.",
          18: "9...Nbd7 adds another defender of e5 and prepares ...b5.",
          19: "10.g4 threatens g5.",
          20: "10...b5 counterattacks; ...b4 is coming.",
          21: "11.Bxf6.",
          22: "11...Nxf6 keeps the pawn structure intact.",
          23: "12.g5 kicks the knight.",
          24: "12...Nd7 retreats to a safe square covering e5 and c5. Black's counterplay with ...b4, ...Bb7 and ...Nc5 comes quickly.",
        },
      },
      {
        id: "b-sic-najdorf-be2",
        name: "Najdorf: 6.Be2 e5",
        moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be2 e5 Nb3 Be7 O-O O-O Be3 Be6 Qd2 Nbd7 a4 Rc8",
        notes: {
          2: "1...c5, the Sicilian, fights for d4 from the side and creates an unbalanced game.",
          4: "2...d6 prepares ...Nf6 and controls e5.",
          6: "3...cxd4 trades a wing pawn for a centre pawn.",
          8: "4...Nf6 attacks e4.",
          10: "5...a6, the Najdorf, takes b5 from White's pieces and prepares ...e5 or ...e6.",
          11: "6.Be2 is the quiet classical line.",
          12: "6...e5 kicks the knight and claims the centre.",
          13: "7.Nb3.",
          14: "7...Be7 develops and prepares castling.",
          15: "8.O-O.",
          16: "8...O-O: king safety before queenside play.",
          17: "9.Be3.",
          18: "9...Be6 fights for d5.",
          19: "10.Qd2.",
          20: "10...Nbd7 heads for b6 or f6 to control d5.",
          21: "11.a4 stops ...b5.",
          22: "11...Rc8 takes the half-open c-file. Black follows up with ...Qc7 and ...Nb6, preparing the freeing ...d5 break.",
        },
      },
      {
        id: "b-sic-alapin",
        name: "vs Alapin: 2.c3 Nf6 3.e5 Nd5",
        moves: "e4 c5 c3 Nf6 e5 Nd5 d4 cxd4 Nf3 Nc6 cxd4 d6 Bc4 Nb6 Bb5 dxe5 Nxe5 Bd7 Nxd7 Qxd7 Nc3 e6 O-O Be7",
        notes: {
          2: "1...c5, the Sicilian, fights for d4 from the side and creates an unbalanced game.",
          3: "2.c3, the Alapin, prepares d4.",
          4: "2...Nf6 attacks e4 at once.",
          5: "3.e5 kicks the knight.",
          6: "3...Nd5 centralises the knight.",
          7: "4.d4.",
          8: "4...cxd4 challenges White's centre and opens the c-file.",
          9: "5.Nf3.",
          10: "5...Nc6 develops and hits d4 and e5.",
          11: "6.cxd4.",
          12: "6...d6 challenges e5 immediately.",
          13: "7.Bc4 attacks the d5 knight.",
          14: "7...Nb6 hits the bishop.",
          15: "8.Bb5 pins the c6 knight.",
          16: "8...dxe5 removes White's advanced pawn.",
          17: "9.Nxe5.",
          18: "9...Bd7 breaks the pin.",
          19: "10.Nxd7.",
          20: "10...Qxd7 recaptures; the queen covers d5 and protects the c6 knight.",
          21: "11.Nc3.",
          22: "11...e6 opens the bishop.",
          23: "12.O-O.",
          24: "12...Be7, and castling next. White's d4 pawn is isolated: blockade it with a knight on d5 and pressure it with ...Rd8.",
        },
      },
    ],
  },
  {
    id: "b-qgd",
    name: "Queen's Gambit Declined",
    eco: "D37",
    side: "black",
    level: "Intermediate",
    summary:
      "The Queen's Gambit Declined (1.d4 d5 2.c4 e6) is one of the most solid defences in chess. Black keeps a firm pawn on d5, develops calmly and frees the position with timely breaks such as ...c5 or ...e5.",
    ideas: [
      "Hold d5 with ...e6, then develop with ...Nf6, ...Be7 and ...O-O.",
      "Free the cramped position by trading pieces: Capablanca's ...dxc4 and ...Nd5, followed by ...e5.",
      "In the Carlsbad structure, bring the knight to the kingside (...Nbd7-f8-g6) or jump to e4 while White pursues the minority attack.",
      "Remember the Elephant Trap: after ...Nbd7 the d5 pawn is not really hanging.",
      "The problem piece is the c8 bishop: free it with ...e5 or ...c5, or develop it to f5 in the Exchange.",
    ],
    lines: [
      {
        id: "b-qgd-orthodox",
        name: "Orthodox: 4.Bg5 Nbd7 and Capablanca's freeing manoeuvre",
        moves: "d4 d5 c4 e6 Nc3 Nf6 Bg5 Nbd7 e3 Be7 Nf3 O-O Rc1 c6 Bd3 dxc4 Bxc4 Nd5 Bxe7 Qxe7 O-O Nxc3 Rxc3 e5",
        notes: {
          2: "1...d5 claims the centre.",
          3: "2.c4, the Queen's Gambit.",
          4: "2...e6 declines the gambit and supports d5 with a pawn.",
          5: "3.Nc3 adds pressure on d5.",
          6: "3...Nf6 develops and defends d5.",
          7: "4.Bg5 pins the knight.",
          8: "4...Nbd7 develops and sets the Elephant Trap: 5.cxd5 exd5 6.Nxd5? loses a piece.",
          9: "5.e3.",
          10: "5...Be7 breaks the pin.",
          11: "6.Nf3.",
          12: "6...O-O: castle before freeing the position.",
          13: "7.Rc1.",
          14: "7...c6 strengthens d5 and prepares ...dxc4 and ...Nd5.",
          15: "8.Bd3.",
          16: "8...dxc4 wins a tempo: the bishop has to move twice.",
          17: "9.Bxc4.",
          18: "9...Nd5! Capablanca's freeing manoeuvre: trade pieces to relieve the cramp.",
          19: "10.Bxe7.",
          20: "10...Qxe7 recaptures; the queen supports the coming ...e5.",
          21: "11.O-O.",
          22: "11...Nxc3 trades another pair of pieces.",
          23: "12.Rxc3.",
          24: "12...e5 frees the c8 bishop. Black has equalised: next come ...exd4 or ...e4 and ...Nf6, with the bishop going to g4 or f5.",
        },
      },
      {
        id: "b-qgd-exchange",
        name: "Exchange Variation: 4.cxd5 exd5 5.Bg5",
        moves: "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 e3 Be7 Bd3 Nbd7 Qc2 O-O Nf3 Re8 O-O Nf8 Rab1 Ne4 Bxe7 Qxe7",
        notes: {
          2: "1...d5 claims the centre.",
          4: "2...e6 supports d5.",
          6: "3...Nf6 develops and defends d5.",
          7: "4.cxd5 is the Exchange Variation.",
          8: "4...exd5 recaptures with the pawn and opens the c8 bishop's diagonal.",
          9: "5.Bg5.",
          10: "5...c6 supports d5 and gives the queen access to b6 and c7.",
          11: "6.e3.",
          12: "6...Be7 breaks the pin.",
          13: "7.Bd3.",
          14: "7...Nbd7 develops, heading for f8 later.",
          15: "8.Qc2.",
          16: "8...O-O: castle before rerouting the knight.",
          17: "9.Nf3.",
          18: "9...Re8 prepares ...Nf8.",
          19: "10.O-O.",
          20: "10...Nf8 heads for g6 or e6 and frees d7 for the bishop.",
          21: "11.Rab1 prepares the minority attack with b4-b5.",
          22: "11...Ne4 trades White's active bishop and uses the e4 outpost.",
          23: "12.Bxe7.",
          24: "12...Qxe7. Black has freed the position and continues with ...Bf5 and ...Nd6 or ...Ng6 for kingside play, meeting b4 with ...a6.",
        },
      },
      {
        id: "b-qgd-bf4",
        name: "vs 4.Nf3 Be7 5.Bf4",
        moves: "d4 d5 c4 e6 Nc3 Nf6 Nf3 Be7 Bf4 O-O e3 c5 dxc5 Bxc5 Qc2 Nc6 a3 Qa5 Rd1 Be7",
        notes: {
          2: "1...d5 claims the centre.",
          4: "2...e6 supports d5.",
          6: "3...Nf6 develops and defends d5.",
          7: "4.Nf3.",
          8: "4...Be7 develops calmly.",
          9: "5.Bf4 develops the bishop outside the pawn chain.",
          10: "5...O-O: castle first, then strike with ...c5.",
          11: "6.e3.",
          12: "6...c5 hits the centre at once.",
          13: "7.dxc5.",
          14: "7...Bxc5 regains the pawn.",
          15: "8.Qc2.",
          16: "8...Nc6 develops and eyes b4 and d4.",
          17: "9.a3 prepares b4.",
          18: "9...Qa5 pins the c3 knight against the white king.",
          19: "10.Rd1.",
          20: "10...Be7 sidesteps b4, which would have hit queen and bishop at once. Black is fully developed and follows up with ...Ne4 or ...dxc4 and active play.",
        },
      },
      {
        id: "b-qgd-elephant-trap",
        name: "Trap: the Elephant Trap (6.Nxd5?)",
        moves: "d4 d5 c4 e6 Nc3 Nf6 Bg5 Nbd7 cxd5 exd5 Nxd5 Nxd5 Bxd8 Bb4+ Qd2 Bxd2+ Kxd2 Kxd8",
        notes: {
          2: "1...d5 claims the centre.",
          4: "2...e6 declines the gambit.",
          6: "3...Nf6 develops and defends d5.",
          7: "4.Bg5 pins the knight.",
          8: "4...Nbd7 looks as if it leaves d5 underprotected.",
          9: "5.cxd5.",
          10: "5...exd5 recaptures; d5 now looks attacked twice and defended once.",
          11: "6.Nxd5?? grabs the pawn, expecting the pinned f6 knight to be unable to recapture.",
          12: "6...Nxd5! The knight is not really pinned: we can give up the queen.",
          13: "7.Bxd8 takes the queen.",
          14: "7...Bb4+! The key check: White must block with the queen.",
          15: "8.Qd2 is forced.",
          16: "8...Bxd2+ wins the queen back.",
          17: "9.Kxd2.",
          18: "9...Kxd8. Black is a whole piece up.",
        },
      },
    ],
  },
  {
    id: "b-kings-indian",
    name: "King's Indian Defence",
    eco: "E60",
    side: "black",
    level: "Advanced",
    summary:
      "The King's Indian lets White build a big centre and then attacks it with ...e5 or ...c5. It is a fighting defence: Black castles quickly, fianchettoes the bishop on g7 and often launches a kingside pawn storm with ...f5-f4 and ...g5.",
    ideas: [
      "Set up with ...Nf6, ...g6, ...Bg7, ...d6 and ...O-O, then strike with ...e5 (or ...c5).",
      "When White closes the centre with d5, attack on the kingside: ...Ne8 or ...Nd7, then ...f5, ...f4 and ...g5-g4.",
      "The g7 bishop is Black's best piece: keep it, even when it looks blocked by the e5 pawn.",
      "Against the Sämisch and the Four Pawns Attack, hit the centre with ...c5 before White completes development.",
      "In the Exchange Variation, the queenless middlegame is fine for Black: play ...c6 and ...cxd5 and use the g7 bishop.",
    ],
    lines: [
      {
        id: "b-kid-mar-del-plata",
        name: "Classical: Mar del Plata 9.Ne1 Nd7",
        moves: "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7 Ne1 Nd7 Be3 f5 f3 f4 Bf2 g5",
        notes: {
          2: "1...Nf6 develops and stops e4 for now.",
          4: "2...g6 prepares the fianchetto.",
          6: "3...Bg7: the bishop will pressure d4 along the long diagonal.",
          7: "4.e4 builds a big centre.",
          8: "4...d6 prepares ...e5 and stops e5.",
          9: "5.Nf3.",
          10: "5...O-O: castle before opening the centre.",
          11: "6.Be2.",
          12: "6...e5 strikes at d4, the main idea of the King's Indian.",
          13: "7.O-O.",
          14: "7...Nc6 increases the pressure on d4.",
          15: "8.d5 closes the centre and gains queenside space.",
          16: "8...Ne7 heads for the kingside and clears the f-pawn.",
          17: "9.Ne1 prepares f3 and the c5 break.",
          18: "9...Nd7 frees the f-pawn.",
          19: "10.Be3.",
          20: "10...f5 is the thematic break.",
          21: "11.f3.",
          22: "11...f4 gains space and kicks the e3 bishop.",
          23: "12.Bf2.",
          24: "12...g5! The pawn storm begins: ...Ng6, ...Rf7, ...h5 and ...g4 follow, while White attacks on the queenside with c5.",
        },
      },
      {
        id: "b-kid-exchange",
        name: "Exchange Variation: 7.dxe5",
        moves: "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 dxe5 dxe5 Qxd8 Rxd8 Bg5 Re8 Nd5 Nxd5 cxd5 c6 Bc4 cxd5",
        notes: {
          2: "1...Nf6 develops and stops e4 for now.",
          4: "2...g6 prepares the fianchetto.",
          6: "3...Bg7: the bishop will pressure d4 along the long diagonal.",
          8: "4...d6 prepares ...e5 and keeps White's e-pawn from advancing to e5.",
          10: "5...O-O: castle before opening the centre.",
          12: "6...e5 strikes at the centre.",
          13: "7.dxe5 heads for an early endgame, hoping for a small edge.",
          14: "7...dxe5 recaptures; the symmetrical centre is fine for Black.",
          15: "8.Qxd8.",
          16: "8...Rxd8 recaptures; the rook takes the open d-file.",
          17: "9.Bg5 hits the f6 knight and the rook on d8 behind it.",
          18: "9...Re8 moves the rook out of the pin and keeps it on the useful e-file.",
          19: "10.Nd5 attacks c7 and f6.",
          20: "10...Nxd5 removes the dangerous knight.",
          21: "11.cxd5.",
          22: "11...c6 challenges the d5 pawn at once.",
          23: "12.Bc4.",
          24: "12...cxd5. After 13.Bxd5 Nd7 Black is fully equal: the knight heads for c5 and the g7 bishop is excellent.",
        },
      },
      {
        id: "b-kid-four-pawns",
        name: "Four Pawns Attack: 5.f4 O-O 6.Nf3 c5",
        moves: "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f4 O-O Nf3 c5 d5 e6 Be2 exd5 cxd5 Bg4 O-O Nbd7 h3 Bxf3 Bxf3 Re8",
        notes: {
          2: "1...Nf6 develops and stops e4 for now.",
          4: "2...g6 prepares the fianchetto.",
          6: "3...Bg7: the bishop will pressure d4 along the long diagonal.",
          8: "4...d6 prepares ...e5 and keeps White's e-pawn from advancing to e5.",
          9: "5.f4, the Four Pawns Attack, builds a huge centre.",
          10: "5...O-O: castle before opening the centre.",
          11: "6.Nf3.",
          12: "6...c5 attacks the centre before White is developed.",
          13: "7.d5.",
          14: "7...e6 breaks up the pawn chain.",
          15: "8.Be2.",
          16: "8...exd5 opens the e-file.",
          17: "9.cxd5.",
          18: "9...Bg4 develops and prepares to trade the knight that controls e5.",
          19: "10.O-O.",
          20: "10...Nbd7 heads for e5 or b6.",
          21: "11.h3.",
          22: "11...Bxf3 gives up the bishop to gain control of e5.",
          23: "12.Bxf3.",
          24: "12...Re8 pressures e4. Black plans ...c4, ...Nc5 and ...Qb6 against White's big but vulnerable centre.",
        },
      },
      {
        id: "b-kid-samisch-dxc5",
        name: "Sämisch: 5.f3 O-O 6.Be3 c5 7.dxc5",
        moves: "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3 O-O Be3 c5 dxc5 dxc5 Qxd8 Rxd8 Bxc5 Nc6",
        notes: {
          2: "1...Nf6 develops and stops e4 for now.",
          4: "2...g6 prepares the fianchetto.",
          6: "3...Bg7: the bishop will pressure d4 along the long diagonal.",
          8: "4...d6 prepares ...e5 and keeps White's e-pawn from advancing to e5.",
          9: "5.f3, the Sämisch, supports e4 and prepares Be3, Qd2 and g4.",
          10: "5...O-O: castle before opening the centre.",
          11: "6.Be3.",
          12: "6...c5! strikes before White's king is safe. It is a real gambit.",
          13: "7.dxc5 accepts.",
          14: "7...dxc5 recaptures and allows the queen trade.",
          15: "8.Qxd8.",
          16: "8...Rxd8 recaptures on the open file. The c5 pawn falls next, but that is the point of the gambit.",
          17: "9.Bxc5 wins a pawn.",
          18: "9...Nc6. Black has a big lead in development and pressure on the dark squares (...Nd7, ...Bxc3, ...Nd4): full compensation for the pawn.",
        },
      },
      {
        id: "b-kid-samisch-nge2",
        name: "Sämisch: 6...c5 7.Nge2 Nc6 8.d5",
        moves: "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3 O-O Be3 c5 Nge2 Nc6 d5 Ne5 Ng3 e6 Be2 exd5 cxd5 a6 a4 h5",
        notes: {
          2: "1...Nf6 develops and stops e4 for now.",
          4: "2...g6 prepares the fianchetto.",
          6: "3...Bg7: the bishop will pressure d4 along the long diagonal.",
          8: "4...d6 prepares ...e5 and keeps White's e-pawn from advancing to e5.",
          9: "5.f3, the Sämisch.",
          10: "5...O-O: castle before opening the centre.",
          11: "6.Be3.",
          12: "6...c5 hits the centre at once.",
          13: "7.Nge2 declines the pawn and keeps developing.",
          14: "7...Nc6 adds pressure on d4.",
          15: "8.d5.",
          16: "8...Ne5 centralises the knight.",
          17: "9.Ng3.",
          18: "9...e6 opens lines in the centre.",
          19: "10.Be2.",
          20: "10...exd5 opens the e-file for our rook.",
          21: "11.cxd5.",
          22: "11...a6 prepares ...b5.",
          23: "12.a4 stops it.",
          24: "12...h5! threatens ...h4 to chase the g3 knight. Black has a good Benoni-style position with active pieces.",
        },
      },
    ],
  },
];
