import type { Opening } from '../types';

// White repertoire: 1.e4 (Italian, Ruy Lopez, Alapin vs the Sicilian, Advance vs French and Caro-Kann)
// plus a 1.d4 option (Queen's Gambit or London System).
export const whiteOpenings: Opening[] = [
  {
    id: "w-italian",
    name: "Italian Game",
    eco: "C50",
    side: "white",
    level: "Beginner",
    summary:
      "The Italian Game puts the bishop on c4, aiming at f7, the square only Black's king protects. Modern players combine it with c3 and d3: a calm build-up that keeps the centre flexible and prepares d4 or a kingside attack once every piece is developed. It is the ideal opening for learning how to manoeuvre in quiet positions.",
    ideas: [
      "Build the c3 + d3 pawn chain, castle, then play Re1, h3 and the knight tour Nbd2-f1-g3 toward the kingside.",
      "Gain queenside space with a4 so the c4 bishop always has a safe retreat on a2 or b3.",
      "Keep the d3-d4 break in reserve and play it only when fully developed: opening the centre helps the side with the better pieces.",
      "A knight on g3 heading for f5, plus Be3 or Bg5, is the typical way to press on the kingside.",
      "Watch f7: tricks with Ng5 and Bxf7+ appear whenever Black neglects that square.",
    ],
    lines: [
      {
        id: "w-italian-pianissimo-d6",
        name: "Giuoco Pianissimo: 4...Nf6 5.d3 d6, the slow build-up",
        moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O a6 a4 Ba7 Re1 O-O h3 h6 Nbd2 Re8 Nf1",
        notes: {
          1: "1.e4 grabs the centre and opens lines for the queen and the king's bishop.",
          2: "Black claims an equal share of the centre.",
          3: "2.Nf3 develops with a threat: the e5 pawn is attacked.",
          4: "The knight defends e5, the most natural reply.",
          5: "3.Bc4 is the Italian Game. The bishop points at f7, which only the black king defends.",
          6: "3...Bc5, the Giuoco Piano: Black's bishop mirrors ours and eyes f2.",
          7: "4.c3 prepares d4 and takes the d4 square away from Black's knight.",
          8: "Black develops and counterattacks e4.",
          9: "5.d3 protects e4 calmly. We keep the centre closed until our development is complete.",
          10: "5...d6 supports e5 and opens the c8 bishop.",
          11: "6.O-O puts the king in safety before any action starts.",
          12: "6...a6 prepares ...Ba7, so the bishop cannot be hit with tempo by b4 or d4.",
          13: "7.a4 gains queenside space and stops ...b5 from chasing our bishop.",
          14: "The bishop drops back to a7, where it still aims at f2.",
          15: "8.Re1 supports e4 and frees the f1 square for our queen's knight.",
          16: "Black castles.",
          17: "9.h3 rules out ...Bg4 pinning our knight and ...Ng4 jumping into our position. Small prophylactic moves like this are typical of the Italian.",
          18: "9...h6 does the same job for Black, keeping our bishop out of g5.",
          19: "10.Nbd2 starts the classic knight tour d2-f1-g3.",
          20: "Black mirrors our set-up and supports e5.",
          21: "11.Nf1 heads for g3, eyeing f5 and h5, or for e3. With every piece developed White can choose between the d3-d4 break and a slow kingside build-up with Ng3, Be3 and Qc2.",
        },
      },
      {
        id: "w-italian-pianissimo-d5",
        name: "Giuoco Pianissimo: Black breaks with 6...d5",
        moves: "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 O-O O-O d5 exd5 Nxd5 Re1 Bg4 h3 Bh5 Nbd2",
        notes: {
          1: "1.e4 occupies the centre and frees the bishop and queen.",
          3: "2.Nf3 develops and attacks e5.",
          5: "3.Bc4, the Italian bishop, aims at f7.",
          7: "4.c3 prepares d4 and gives the bishop a future retreat on b3 and c2.",
          9: "5.d3 protects e4 and keeps the centre closed while we develop.",
          10: "5...O-O: Black castles first, planning the active ...d5 break.",
          11: "6.O-O: king safety first, before the centre opens.",
          12: "6...d5 is Black's most active plan: open the centre while our queenside is still at home.",
          13: "7.exd5 is the simplest answer. The black knight comes to d5, where it can be harassed, and e5 loses a defender.",
          14: "The knight recaptures in the centre, but e5 is now weak.",
          15: "8.Re1 attacks e5 at once, so Black must spend time on defence.",
          16: "8...Bg4 pins our knight: 9.Nxe5?? would now drop the queen to ...Bxd1.",
          17: "9.h3 asks the bishop a question: give up the bishop pair on f3, or retreat.",
          18: "The bishop keeps the pin from h5.",
          19: "10.Nbd2 develops and heads for e4 (hitting the c5 bishop) or f1-g3. With a4, b4 or Ne4 to come, White has an easy, slightly better game.",
        },
      },
      {
        id: "w-italian-two-knights-d3",
        name: "Two Knights Defence: 3...Nf6 4.d3",
        moves: "e4 e5 Nf3 Nc6 Bc4 Nf6 d3 Be7 O-O O-O Re1 d6 c3 Na5 Bb5 a6 Ba4 b5 Bc2 c5 Nbd2 Nc6 Nf1",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.Nf3 develops with a threat to e5.",
          5: "3.Bc4 develops the bishop toward f7.",
          6: "3...Nf6 is the Two Knights Defence: Black attacks e4 at once instead of developing the bishop.",
          7: "4.d3 simply protects e4. We avoid the sharp 4.Ng5 theory and keep a solid, flexible centre.",
          8: "4...Be7 is a calm set-up; Black prepares to castle.",
          9: "5.O-O: castle quickly.",
          11: "6.Re1 adds a second defender to e4 and prepares Nbd2-f1.",
          12: "Black supports e5.",
          13: "7.c3 prepares d4 and creates the c2 square for our bishop.",
          14: "7...Na5 chases our strong bishop and hopes to trade it.",
          15: "8.Bb5! sidesteps the trade. Black has to spend more moves pushing our bishop, and we get a Ruy Lopez-style position.",
          16: "Black attacks the bishop again.",
          17: "9.Ba4 keeps the bishop on the a4-e8 diagonal for one more move.",
          18: "9...b5 gains space but loosens Black's queenside.",
          19: "10.Bc2 is the ideal post: the bishop is safe, supports a later d4 and eyes the kingside.",
          20: "Black grabs queenside space.",
          21: "11.Nbd2 starts the standard knight route to f1 and g3.",
          22: "The knight returns to the centre, where it watches d4.",
          23: "12.Nf1 heads for g3 or e3. White plans h3, Ng3 and d4 at the right moment, with a typical Spanish-style game.",
        },
      },
      {
        id: "w-italian-fried-liver-trap",
        name: "Trap: Fried Liver Attack (4.Ng5 d5 5.exd5 Nxd5?)",
        moves: "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nb4 O-O c6 d4",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.Nf3 develops and attacks e5.",
          5: "3.Bc4 aims at f7.",
          6: "3...Nf6, the Two Knights. Our main answer is 4.d3; this line shows the sharp alternative and the trap that catches many club players.",
          7: "4.Ng5 attacks f7 twice, with knight and bishop. Only the king defends it.",
          8: "4...d5 is Black's correct way to block the bishop.",
          9: "5.exd5 wins a pawn and attacks the c6 knight.",
          10: "5...Nxd5? is the natural mistake. The correct move is 5...Na5, hitting our bishop.",
          11: "6.Nxf7! sacrifices the knight to drag the king into the open: the Fried Liver Attack.",
          12: "Black has to take, otherwise the knight forks queen and rook.",
          13: "7.Qf3+ checks the king and attacks the pinned knight on d5 at the same time.",
          14: "7...Ke6 is the only way to keep the knight; other king moves lose it to Bxd5 with a winning attack.",
          15: "8.Nc3 piles up on the pinned knight: it is now attacked three times.",
          16: "8...Nb4 adds a defender to d5 and eyes a fork on c2.",
          17: "9.O-O puts our king in safety and brings the rook toward the e-file.",
          18: "Black supports d5 once more.",
          19: "10.d4! rips the centre open while Black's king is stuck on e6. Re1, Bg5 and a3 to kick the b4 knight follow, and White's attack is worth far more than the piece.",
        },
      },
    ],
  },
  {
    id: "w-ruy-lopez",
    name: "Ruy Lopez",
    eco: "C60",
    side: "white",
    level: "Intermediate",
    summary:
      "The Ruy Lopez (Spanish Game) attacks the knight that defends e5 and builds long-term pressure rather than an instant attack. It is the classical way to play for an advantage after 1.e4 e5, rich in manoeuvring plans that every club player should know.",
    ideas: [
      "Keep pressure on e5: the bishop on b5, a4 or b3 targets the knight that defends it, so Black is always slightly tied up.",
      "Build the ideal centre with c3 and d4, prepared by Re1 and h3 so that ...Bg4 and ...Ng4 are ruled out.",
      "Reroute the queen's knight via d2-f1-g3 toward the kingside, where it supports Nf5 or a pawn advance.",
      "Retreat the bishop to c2 when attacked: from there it points straight at the black king.",
      "In the Exchange Variation, head for an endgame where your healthy 4-vs-3 kingside majority creates a passed pawn and Black's doubled c-pawns cannot.",
    ],
    lines: [
      {
        id: "w-ruy-chigorin",
        name: "Closed Ruy Lopez: Chigorin 9...Na5",
        moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Na5 Bc2 c5 d4 Qc7 Nbd2",
        notes: {
          1: "1.e4 occupies the centre.",
          3: "2.Nf3 develops with a threat to e5.",
          5: "3.Bb5 attacks the knight that defends e5. This is the Ruy Lopez.",
          6: "3...a6, the Morphy Defence, questions the bishop at once.",
          7: "4.Ba4 keeps the pressure on c6. Taking on c6 is the Exchange Variation; here we keep the tension.",
          8: "Black develops and attacks e4.",
          9: "5.O-O. We don't need to defend e4 yet: after 5...Nxe4, Re1 or d4 wins the pawn back with a good game.",
          10: "5...Be7 is the Closed Ruy Lopez: Black prepares to castle.",
          11: "6.Re1 protects e4. Now we really threaten Bxc6 followed by Nxe5.",
          12: "6...b5 drives the bishop away and removes that threat.",
          13: "7.Bb3 keeps the bishop on the a2-g8 diagonal, still aiming at f7.",
          14: "Black supports e5 and opens the c8 bishop.",
          15: "8.c3 prepares d4 and gives the bishop a home on c2.",
          16: "Black castles.",
          17: "9.h3 is essential before d4: it stops ...Bg4 pinning the knight that will support d4.",
          18: "9...Na5 is the Chigorin: the knight hits our bishop and clears the way for ...c5.",
          19: "10.Bc2 keeps the bishop on the b1-h7 diagonal, aiming at Black's king.",
          20: "Black gains queenside space and prepares to pressure d4.",
          21: "11.d4 builds the ideal centre now that everything is prepared.",
          22: "The queen adds pressure on d4 and supports e5.",
          23: "12.Nbd2 heads for f1 and g3 (or e3). White's plans are Nf1-g3, sometimes d5 to close the centre, and then a kingside attack.",
        },
      },
      {
        id: "w-ruy-breyer",
        name: "Closed Ruy Lopez: Breyer 9...Nb8",
        moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Nb8 d4 Nbd7 Nbd2 Bb7 Bc2",
        notes: {
          1: "1.e4 occupies the centre.",
          3: "2.Nf3 attacks e5.",
          5: "3.Bb5, the Ruy Lopez, pressures the defender of e5.",
          7: "4.Ba4 keeps the bishop and the pressure.",
          9: "5.O-O: e4 is indirectly protected, so we castle first.",
          11: "6.Re1 defends e4 and threatens Bxc6 and Nxe5.",
          13: "7.Bb3 retreats while keeping an eye on f7.",
          15: "8.c3 prepares d4 and a retreat square on c2.",
          17: "9.h3 prepares d4 without allowing ...Bg4.",
          18: "9...Nb8 is the Breyer: the knight goes back to reroute via d7, where it supports e5 and frees the c-pawn.",
          19: "10.d4 claims the centre while Black is regrouping.",
          20: "The knight arrives on d7 and defends e5.",
          21: "11.Nbd2 continues our standard development toward f1.",
          22: "The bishop adds pressure on e4.",
          23: "12.Bc2 protects e4 a second time so the d2 knight can leave. Next come Nf1-g3 and possibly a4 or b4 to probe the queenside.",
        },
      },
      {
        id: "w-ruy-berlin",
        name: "Berlin Defence: 4.O-O Nxe4 5.Re1",
        moves: "e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5 Rxe5 O-O d4 Bf6 Re1",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.Nf3 attacks e5.",
          5: "3.Bb5, the Ruy Lopez.",
          6: "3...Nf6 is the Berlin Defence, the most solid reply at top level.",
          7: "4.O-O. We can let e4 go because the rook will win it back.",
          8: "Black grabs the pawn.",
          9: "5.Re1 attacks the knight and avoids the queen trade that follows 5.d4 Nd6 6.Bxc6 dxc6 7.dxe5 Nf5 8.Qxd8+.",
          10: "The knight retreats and attacks our bishop.",
          11: "6.Nxe5 regains the pawn at once, even though our bishop is attacked.",
          12: "6...Be7 prepares to castle. 6...Nxb5?? would lose the queen to 7.Nxc6+, a discovered check from the e1 rook.",
          13: "7.Bf1 brings the bishop back to safety and keeps our pieces coordinated.",
          14: "Black trades knights.",
          15: "8.Rxe5 recaptures; the rook is active on the fifth rank.",
          16: "Black castles.",
          17: "9.d4 takes the centre and frees the c1 bishop.",
          18: "The bishop hits d4 and our rook.",
          19: "10.Re1 retreats to the open file. White has more space and easy development with c3, Bf4 or Bd3 and Nd2-f3.",
        },
      },
      {
        id: "w-ruy-exchange",
        name: "Exchange Variation: 4.Bxc6",
        moves: "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6 O-O f6 d4 exd4 Nxd4 c5 Nb3 Qxd1 Rxd1 Bg4 f3 Be6 Nc3 Bd6 Be3",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.Nf3 attacks e5.",
          5: "3.Bb5, the Ruy Lopez.",
          7: "4.Bxc6 gives up the bishop pair to double Black's pawns. It is a practical alternative to 4.Ba4 with a very clear plan.",
          8: "Black recaptures toward the centre, opening lines for the bishops.",
          9: "5.O-O. Not 5.Nxe5 at once, because 5...Qd4 wins the pawn back.",
          10: "5...f6 solidly protects e5.",
          11: "6.d4 opens the centre to trade queens. The endgame suits us, because our pawn majority is healthy.",
          12: "Black exchanges.",
          13: "7.Nxd4 recaptures with the knight, centralising it.",
          14: "Black kicks the knight and gains space.",
          15: "8.Nb3 retreats and offers the queen trade.",
          16: "Black exchanges queens.",
          17: "9.Rxd1 recaptures; the rook takes the open d-file.",
          18: "The bishop develops with a threat against the d1 rook.",
          19: "10.f3 blocks the bishop and supports e4.",
          20: "The bishop retreats and eyes our b3 knight.",
          21: "11.Nc3 develops.",
          22: "Black develops.",
          23: "12.Be3 completes development. The plan: a4-a5 on the queenside, then advance the kingside pawns (f4, e5) to create a passed pawn, which Black's doubled c-pawns cannot match.",
        },
      },
    ],
  },
  {
    id: "w-alapin",
    name: "Sicilian Alapin (2.c3)",
    eco: "B22",
    side: "white",
    level: "Intermediate",
    summary:
      "The Alapin answers the Sicilian with 2.c3, preparing d4 so that White can recapture with a pawn and keep a full centre. It avoids the huge body of Open Sicilian theory and leads to clear positions, often with an isolated queen's pawn and active pieces for White.",
    ideas: [
      "Play d4 and recapture with the c-pawn to keep two pawns in the centre.",
      "Against 2...d5, develop quickly with Nf3, Be2 and O-O, then gain time by hitting the black queen with Nc3.",
      "With an isolated d4 pawn, keep pieces on the board: Bd3 or Bb5, Re1, Ne5 and the d4-d5 break are your attacking tools.",
      "Against 2...Nf6, push e5 to kick the knight, then use Bc4-b5 to put pressure on the black knights.",
    ],
    lines: [
      {
        id: "w-alapin-nf6",
        name: "2...Nf6 3.e5 Nd5 4.d4",
        moves: "e4 c5 c3 Nf6 e5 Nd5 d4 cxd4 Nf3 Nc6 cxd4 d6 Bc4 Nb6 Bb5 dxe5 Nxe5 Bd7 Nxd7 Qxd7 Nc3 e6 O-O",
        notes: {
          1: "1.e4 takes the centre.",
          2: "1...c5 is the Sicilian Defence.",
          3: "2.c3 prepares d4, so that ...cxd4 can be met by cxd4 with a big pawn centre.",
          4: "2...Nf6 attacks e4, which can no longer be defended by Nc3.",
          5: "3.e5 gains space with tempo on the knight.",
          6: "The knight jumps to the strong central square d5.",
          7: "4.d4 builds the centre and supports e5.",
          8: "Black exchanges.",
          9: "5.Nf3 develops first; we recapture on d4 next move.",
          10: "Black develops and adds pressure on d4 and e5.",
          11: "6.cxd4 restores the pawn centre.",
          12: "Black immediately challenges e5.",
          13: "7.Bc4 hits the d5 knight and develops.",
          14: "The knight retreats to b6 and attacks our bishop.",
          15: "8.Bb5 pins the c6 knight. If Black takes on e5, our knight recaptures and hits the pinned piece.",
          16: "Black takes on e5.",
          17: "9.Nxe5 recaptures and presses on the pinned c6 knight.",
          18: "Black breaks the pin by covering c6.",
          19: "10.Nxd7 removes the bishop, so the queen must recapture.",
          20: "Black recaptures.",
          21: "11.Nc3 develops and controls d5 and e4.",
          22: "Black prepares ...Be7 and castling.",
          23: "12.O-O. White has an isolated d-pawn but active pieces; plans include Qg4, Be3 and the d4-d5 break.",
        },
      },
      {
        id: "w-alapin-d5",
        name: "2...d5 3.exd5 Qxd5 4.d4",
        moves: "e4 c5 c3 d5 exd5 Qxd5 d4 Nf6 Nf3 e6 Be2 Nc6 O-O cxd4 cxd4 Be7 Nc3 Qd6 Nb5 Qd8 Bf4",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.c3 prepares d4.",
          4: "2...d5 hits the centre at once.",
          5: "3.exd5 is simplest: the black queen must recapture and will become a target.",
          6: "Because c3 is occupied by a pawn, we cannot hit the queen at once, but Nc3 will come later with tempo.",
          7: "4.d4 builds the centre and opens the c1 bishop.",
          8: "Black develops.",
          9: "5.Nf3 develops.",
          10: "Black opens the f8 bishop.",
          11: "6.Be2 is modest but solid and prepares castling.",
          12: "Black develops and pressures d4.",
          13: "7.O-O: king safety first.",
          14: "Black resolves the central tension.",
          15: "8.cxd4 leaves us an isolated d-pawn, but our pieces get open lines and the c3 square for the knight.",
          16: "Black develops.",
          17: "9.Nc3 develops with tempo on the queen.",
          18: "The queen steps back to d6.",
          19: "10.Nb5 hits the queen again and eyes c7.",
          20: "The queen retreats to d8.",
          21: "11.Bf4 controls c7 and b8 and completes development. White continues with Rc1, Ne5 and the d4-d5 break.",
        },
      },
      {
        id: "w-alapin-nc6",
        name: "2...Nc6 3.d4 d5",
        moves: "e4 c5 c3 Nc6 d4 d5 exd5 Qxd5 Nf3 Bg4 Be2 cxd4 cxd4 e6 Nc3 Qa5 O-O Nf6 h3 Bh5 a3",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.c3 prepares d4.",
          4: "2...Nc6 develops and keeps an eye on d4.",
          5: "3.d4 claims the centre at once.",
          6: "Black strikes back in the centre.",
          7: "4.exd5 opens the position; Black's queen must recapture and can be harassed.",
          8: "The queen centralises and eyes d4.",
          9: "5.Nf3 defends d4 and develops.",
          10: "Black pins the knight to add pressure on d4.",
          11: "6.Be2 breaks the pin.",
          12: "Black exchanges.",
          13: "7.cxd4 keeps a pawn in the centre.",
          14: "Black supports d5 and opens the f8 bishop.",
          15: "8.Nc3 develops with tempo on the queen.",
          16: "The queen goes to a5 and pins our knight against the king.",
          17: "9.O-O ends the pin at once.",
          18: "Black develops.",
          19: "10.h3 asks the bishop: give up the bishop pair on f3, or retreat.",
          20: "The bishop keeps the pin from h5.",
          21: "11.a3 prepares b4, which will chase the queen and gain queenside space. Our pieces are active and d4 is well protected.",
        },
      },
    ],
  },
  {
    id: "w-french-advance",
    name: "French Defence: Advance Variation",
    eco: "C02",
    side: "white",
    level: "Intermediate",
    summary:
      "Against the French (1...e6 and 2...d5) we push 3.e5 and grab space. Black's light-squared bishop stays locked behind the e6 pawn, while White supports the d4-e5 chain with c3 and Nf3 and prepares a kingside attack.",
    ideas: [
      "Defend d4, the base of the chain, with c3, Nf3 and sometimes Nc2: if d4 falls, e5 falls with it.",
      "Gain queenside space with a3 and b4 to blunt ...c5 and ...Qb6 play.",
      "Keep the e5 pawn: it cramps Black and takes f6 and d6 away from his pieces.",
      "Once the centre is secure, attack on the kingside, where you have more space.",
    ],
    lines: [
      {
        id: "w-french-advance-qb6-c4",
        name: "5...Qb6 6.a3 c4",
        moves: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 c4 Nbd2 Na5 Rb1 Bd7 Be2 Ne7 O-O",
        notes: {
          1: "1.e4 takes the centre.",
          2: "1...e6 is the French Defence.",
          3: "2.d4 builds the ideal pawn centre.",
          4: "Black attacks e4.",
          5: "3.e5, the Advance Variation, grabs space and locks Black's light-squared bishop behind the e6 pawn.",
          6: "3...c5 is the standard counterattack against the base of our chain.",
          7: "4.c3 supports d4 with a pawn.",
          8: "Black adds pressure on d4.",
          9: "5.Nf3 develops and defends d4 again.",
          10: "5...Qb6 hits d4 and b2 at the same time.",
          11: "6.a3 prepares b4, gaining queenside space and taking c5 away from Black.",
          12: "6...c4 closes the queenside and stops b4 for now; Black plans ...Na5-b3.",
          13: "7.Nbd2 develops and watches the b3 and c4 squares.",
          14: "The knight heads for b3.",
          15: "8.Rb1 protects b2, so Black's queen has no target, and prepares b3 or b4 to break Black's grip.",
          16: "Black develops.",
          17: "9.Be2 develops and prepares castling.",
          18: "The knight heads for f5 or c6.",
          19: "10.O-O. With the queenside closed, White turns to the kingside: Ne1, f4-f5 or h4-h5, while Black's pieces are stuck on the other wing.",
        },
      },
      {
        id: "w-french-advance-bd7-na3",
        name: "5...Bd7 6.Be2 Nge7 7.Na3",
        moves: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Bd7 Be2 Nge7 Na3 cxd4 cxd4 Nf5 Nc2 Qb6 O-O",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.d4 builds the pawn centre.",
          5: "3.e5 gains space and shuts in the c8 bishop.",
          7: "4.c3 supports d4.",
          9: "5.Nf3 develops and defends d4.",
          10: "5...Bd7 prepares ...Qb6 and ...Nge7-f5 without allowing checks on the a4-e8 diagonal.",
          11: "6.Be2 develops and prepares castling.",
          12: "The knight is heading for f5 to attack d4.",
          13: "7.Na3! The knight heads for c2, where it defends d4 perfectly.",
          14: "Black exchanges on d4.",
          15: "8.cxd4 keeps the centre.",
          16: "The knight lands on f5, attacking d4 for the third time.",
          17: "9.Nc2 defends d4 again; Black's pressure is neutralised.",
          18: "The queen joins the attack on d4 and eyes b2.",
          19: "10.O-O. d4 is safe (Nc2, Nf3 and the queen protect it), and White can continue with g4 to kick the f5 knight or Bd3 to exchange it.",
        },
      },
      {
        id: "w-french-advance-qb6-nh6",
        name: "5...Qb6 6.a3 Nh6 7.b4",
        moves: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Be7 Bd3",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.d4 builds the pawn centre.",
          5: "3.e5 gains space.",
          7: "4.c3 supports d4.",
          9: "5.Nf3 develops and defends d4.",
          10: "5...Qb6 hits d4 and b2.",
          11: "6.a3 prepares b4.",
          12: "6...Nh6 heads for f5 to attack d4 again.",
          13: "7.b4 grabs queenside space and forces Black to decide about c5.",
          14: "Black exchanges.",
          15: "8.cxd4 recaptures; the b4 pawn shields our queenside.",
          16: "The knight arrives on f5 and hits d4.",
          17: "9.Bb2 defends d4.",
          18: "Black develops.",
          19: "10.Bd3 challenges the strong f5 knight. After Bxf5 exf5 White keeps a comfortable space advantage, then castles and brings the knight to c3.",
        },
      },
    ],
  },
  {
    id: "w-caro-advance",
    name: "Caro-Kann Defence: Advance Variation",
    eco: "B12",
    side: "white",
    level: "Intermediate",
    summary:
      "Against the Caro-Kann (1...c6 and 2...d5) we again push 3.e5. Black's bishop escapes to f5 before ...e6, so White fights with rapid development (Nf3, Be2, O-O) and flexible plans: the c4 break against the centre, or a quiet squeeze with Nbd2-b3 controlling c5.",
    ideas: [
      "Develop quickly with Nf3, Be2 and O-O (the Short System) and keep the e5 wedge.",
      "If Black plays ...c5, support d4 with Be3 and recapture on d4 with the knight to keep central control.",
      "The c2-c4 break opens lines when you are ahead in development.",
      "Nbd2-b3 fights for c5, Black's key break square; Nh4 can harass the f5 bishop.",
    ],
    lines: [
      {
        id: "w-caro-advance-short-c5",
        name: "Short System: 5...c5 6.Be3",
        moves: "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 cxd4 Nxd4 Ne7 c4",
        notes: {
          1: "1.e4 takes the centre.",
          2: "1...c6 is the Caro-Kann: Black prepares ...d5 without blocking the c8 bishop.",
          3: "2.d4 builds the pawn centre.",
          4: "Black challenges e4.",
          5: "3.e5 gains space; Black's knight can no longer use f6.",
          6: "3...Bf5 develops the bishop before playing ...e6.",
          7: "4.Nf3 is the Short System: quick, simple development.",
          8: "Black supports d5.",
          9: "5.Be2 prepares castling.",
          10: "5...c5 strikes at the pawn chain.",
          11: "6.Be3 defends d4 and invites ...cxd4 Nxd4, centralising our knight.",
          12: "Black exchanges.",
          13: "7.Nxd4 recaptures with a piece; the knight eyes the f5 bishop.",
          14: "The knight heads for c6 or g6.",
          15: "8.c4! hits d5 while we are ahead in development. If ...dxc4, Qa4+ or Nc3 opens the game in our favour.",
        },
      },
      {
        id: "w-caro-advance-short-nd7",
        name: "Short System: 5...Nd7 6.O-O",
        moves: "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 Nd7 O-O Ne7 Nbd2 h6 Nb3",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.d4 builds the pawn centre.",
          5: "3.e5, the Advance Variation.",
          7: "4.Nf3, the Short System.",
          9: "5.Be2 prepares castling.",
          10: "5...Nd7 keeps options open: ...c5 or ...Ne7 come next.",
          11: "6.O-O puts the king in safety first.",
          12: "Black develops toward f5 or g6.",
          13: "7.Nbd2 heads for b3 to control c5 and stop Black's main break.",
          14: "7...h6 gives the bishop a retreat on h7.",
          15: "8.Nb3 controls c5. White continues with c3, Bd2 and a4-a5 on the queenside, keeping Black cramped.",
        },
      },
      {
        id: "w-caro-advance-c5",
        name: "3...c5 4.dxc5",
        moves: "e4 c6 d4 d5 e5 c5 dxc5 Nc6 Bb5 e6 Be3 Ne7 Nf3 Bd7 Bxc6 Nxc6 O-O",
        notes: {
          1: "1.e4 takes the centre.",
          3: "2.d4 builds the pawn centre.",
          5: "3.e5 gains space.",
          6: "3...c5 spends a second tempo on the c-pawn but hits d4 at once.",
          7: "4.dxc5 takes the pawn; Black must spend time winning it back.",
          8: "Black develops and prepares to regain c5.",
          9: "5.Bb5 pins the knight, which would otherwise attack e5.",
          10: "Black prepares to recapture on c5 with the bishop.",
          11: "6.Be3 defends the extra pawn on c5.",
          12: "6...Ne7 heads for c6 or f5, where it can hit the e3 bishop.",
          13: "7.Nf3 protects e5 and develops.",
          14: "Black breaks the pin.",
          15: "8.Bxc6 gives up the bishop to keep control of e5 and c5.",
          16: "Black recaptures with the knight.",
          17: "9.O-O. Black will regain the pawn with ...Be7xc5 or ...Qc7, but White keeps a lead in development and the space-gaining pawn on e5.",
        },
      },
    ],
  },
  {
    id: "w-queens-gambit",
    name: "Queen's Gambit",
    eco: "D06",
    side: "white",
    level: "Intermediate",
    summary:
      "The Queen's Gambit offers the c-pawn to lure Black's d-pawn away from the centre. It is not a real gambit: White either regains the pawn or keeps a lasting central advantage. The lines below teach the key 1.d4 middlegame structures: the Carlsbad, the isolated queen's pawn and the Slav.",
    ideas: [
      "Use c4 to attack d5; if Black gives up the centre with ...dxc4, regain the pawn with e3 and Bxc4 and enjoy the extra central pawn.",
      "In the QGD, develop with Nc3, Bg5, e3, Nf3, Rc1 and Bd3 and keep Black's c8 bishop passive.",
      "In the Carlsbad structure (after cxd5 exd5), play the minority attack: Rb1 and b4-b5 to leave Black with a weak c- or d-pawn.",
      "With an isolated queen's pawn, keep pieces on, post knights on e5 and c3, and prepare the d4-d5 break.",
    ],
    lines: [
      {
        id: "w-qg-qgd-orthodox",
        name: "QGD Orthodox: 4...Be7 5.e3 O-O 6.Nf3 Nbd7 7.Rc1",
        moves: "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 Nbd7 Rc1 c6 Bd3 dxc4 Bxc4 Nd5 Bxe7 Qxe7 O-O Nxc3 Rxc3",
        notes: {
          1: "1.d4 takes the centre; the pawn is already protected by the queen.",
          2: "Black mirrors.",
          3: "2.c4 is the Queen's Gambit: the pawn attacks d5 and prepares Nc3.",
          4: "2...e6 is the Queen's Gambit Declined, holding d5 with a pawn.",
          5: "3.Nc3 adds pressure on d5.",
          6: "Black develops and defends d5.",
          7: "4.Bg5 pins the knight, weakening Black's control of d5.",
          8: "Black breaks the pin.",
          9: "5.e3 opens the way for the f1 bishop.",
          10: "Black castles.",
          11: "6.Nf3 develops.",
          12: "Black develops, preparing ...c5 or ...e5 later.",
          13: "7.Rc1 puts the rook on the c-file, useful if Black ever plays ...dxc4 or ...c5.",
          14: "Black supports d5 and prepares ...dxc4.",
          15: "8.Bd3 develops. If Black takes on c4, the bishop moves twice, but we gain central control.",
          16: "Black captures now that our bishop has moved.",
          17: "9.Bxc4 recaptures.",
          18: "9...Nd5 is Capablanca's freeing manoeuvre: trade pieces to ease Black's cramped position.",
          19: "10.Bxe7 exchanges; keeping the bishop with Bg3 would allow ...Nxc3 anyway.",
          20: "Black recaptures.",
          21: "11.O-O. We don't fear the knight trade on c3, because the rook recaptures.",
          22: "Black continues trading.",
          23: "12.Rxc3. Black will play ...e5 to free the c8 bishop; White keeps a small edge with active pieces, usually Bb3, Qc2 and pressure on the c-file.",
        },
      },
      {
        id: "w-qg-carlsbad",
        name: "QGD 4...Nbd7: 5.cxd5 and the minority attack",
        moves: "d4 d5 c4 e6 Nc3 Nf6 Bg5 Nbd7 cxd5 exd5 e3 c6 Bd3 Be7 Qc2 O-O Nf3 Re8 O-O Nf8 Rab1",
        notes: {
          1: "1.d4 takes the centre.",
          3: "2.c4, the Queen's Gambit.",
          5: "3.Nc3 adds pressure on d5.",
          7: "4.Bg5 pins the knight.",
          8: "4...Nbd7 sets a trap: the d5 pawn looks loose, but it is not.",
          9: "5.cxd5 releases the tension and creates the Carlsbad pawn structure.",
          10: "Black recaptures with the pawn.",
          11: "6.e3! Not 6.Nxd5?? Nxd5 7.Bxd8 Bb4+ 8.Qd2 Bxd2+ 9.Kxd2 Kxd8, when Black is a piece up (the Elephant Trap).",
          12: "Black secures d5 and gives the queen access to c7 and b6.",
          13: "7.Bd3 develops toward the kingside.",
          14: "Black develops.",
          15: "8.Qc2 lines up with the bishop on the b1-h7 diagonal and stops ...Bf5.",
          16: "Black castles.",
          17: "9.Nf3 develops.",
          18: "Black prepares ...Nf8 and ...Ne6 or ...Ng6.",
          19: "10.O-O.",
          20: "The knight reroutes to defend the kingside.",
          21: "11.Rab1 prepares the minority attack: b4-b5 and bxc6 to leave Black with a weak c-pawn or d-pawn.",
        },
      },
      {
        id: "w-qg-qga",
        name: "Queen's Gambit Accepted: 2...dxc4 3.Nf3",
        moves: "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 a4 Nc6 Qe2 cxd4 Rd1 Be7 exd4 O-O Nc3",
        notes: {
          1: "1.d4 takes the centre.",
          3: "2.c4, the Queen's Gambit.",
          4: "2...dxc4 accepts the pawn but gives up the centre.",
          5: "3.Nf3 prevents ...e5 and prepares e3.",
          6: "Black develops.",
          7: "4.e3 opens the bishop's diagonal to regain the pawn.",
          8: "Black prepares ...c5.",
          9: "5.Bxc4 regains the pawn.",
          10: "Black hits our centre.",
          11: "6.O-O.",
          12: "Black prepares ...b5 to gain space with tempo on our bishop.",
          13: "7.a4 stops ...b5.",
          14: "Black develops, adding pressure on d4.",
          15: "8.Qe2 prepares Rd1 and supports a later e4 or d5.",
          16: "Black exchanges on d4.",
          17: "9.Rd1! We recapture next move; the rook on d1 will support the d-pawn.",
          18: "Black develops.",
          19: "10.exd4 recaptures, leaving us with an isolated queen's pawn.",
          20: "Black castles.",
          21: "11.Nc3. White plans Bg5, Ne5 and d4-d5 with active pieces, while Black aims to blockade on d5.",
        },
      },
      {
        id: "w-qg-slav",
        name: "Slav: 2...c6 3.Nf3 Nf6 4.Nc3 dxc4 5.a4",
        moves: "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O O-O Qe2 Nbd7 e4 Bg6 Bd3 Bh5 e5",
        notes: {
          1: "1.d4 takes the centre.",
          3: "2.c4, the Queen's Gambit.",
          4: "2...c6 is the Slav: d5 is defended without blocking the c8 bishop.",
          5: "3.Nf3 develops.",
          6: "Black develops.",
          7: "4.Nc3 adds pressure on d5.",
          8: "Black takes on c4, hoping to hold the pawn with ...b5.",
          9: "5.a4 stops ...b5, so we can win the pawn back.",
          10: "The bishop develops outside the pawn chain.",
          11: "6.e3 prepares Bxc4.",
          12: "Black supports the centre.",
          13: "7.Bxc4 regains the pawn.",
          14: "Black pins the c3 knight.",
          15: "8.O-O.",
          16: "Black castles.",
          17: "9.Qe2 prepares e4.",
          18: "Black develops.",
          19: "10.e4 grabs the centre with tempo on the f5 bishop.",
          20: "The bishop retreats.",
          21: "11.Bd3 supports e4 and blunts the g6 bishop.",
          22: "Black keeps the pin on f3.",
          23: "12.e5 kicks the f6 knight and gains space. White follows up with Ne4 or Qe3 and a kingside initiative.",
        },
      },
    ],
  },
  {
    id: "w-london",
    name: "London System",
    eco: "D02",
    side: "white",
    level: "Beginner",
    summary:
      "The London System is a set-up rather than a body of theory: d4, Bf4, e3, Nf3, c3, Nbd2 and Bd3 against almost anything. It is solid, quick to learn, and gives a clear attacking plan with Ne5 and a kingside pawn advance.",
    ideas: [
      "Develop the dark-squared bishop to f4 before playing e3, so it is not locked in.",
      "Build the c3-d4-e3 pyramid, then Bd3, Nbd2 and castle: the structure is very hard to break.",
      "When Black's bishop comes to d6, retreat Bg3 instead of trading, and keep the bishop.",
      "Attack with Ne5, f4 and Qf3-h3, or with a pawn storm when Black castles kingside.",
      "Against ...Qb6 hitting b2, answer Qb3: if queens are traded, the a-file opens for your rook.",
    ],
    lines: [
      {
        id: "w-london-classical",
        name: "vs ...d5, ...e6, ...c5 and ...Bd6",
        moves: "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 Ne5 Bb7 f4 Ne7 Qf3",
        notes: {
          1: "1.d4 takes the centre.",
          3: "2.Bf4 develops the bishop before e3 closes its diagonal. This is the London.",
          4: "Black develops.",
          5: "3.e3 supports d4 and opens the f1 bishop.",
          6: "Black prepares ...c5 and ...Bd6.",
          7: "4.Nf3 develops.",
          8: "Black hits d4.",
          9: "5.c3 completes the pyramid; d4 is now rock solid.",
          10: "Black develops.",
          11: "6.Nbd2 supports e4 and keeps c3 for the pawn.",
          12: "Black offers to trade our good bishop.",
          13: "7.Bg3 keeps the bishop. If Black takes on g3, hxg3 opens the h-file for our rook.",
          14: "Black castles.",
          15: "8.Bd3 aims at h7.",
          16: "Black prepares ...Bb7.",
          17: "9.Ne5 occupies the key outpost in front of Black's position.",
          18: "Black develops.",
          19: "10.f4 supports the knight: the attacking Stonewall-style set-up.",
          20: "The knight heads for f5 or g6 to defend the kingside.",
          21: "11.Qf3 heads for h3 to join the attack; g4-g5 ideas are next.",
        },
      },
      {
        id: "w-london-qb6",
        name: "vs ...c5 and ...Qb6: 6.Qb3",
        moves: "d4 d5 Bf4 Nf6 e3 c5 c3 Nc6 Nd2 Qb6 Qb3 e6 Ngf3 Bd7 Be2 Be7 O-O O-O Qc2",
        notes: {
          1: "1.d4 takes the centre.",
          3: "2.Bf4, the London bishop.",
          5: "3.e3 supports d4.",
          6: "3...c5 is Black's most active set-up.",
          7: "4.c3 supports d4.",
          8: "Black develops.",
          9: "5.Nd2 develops the queen's knight first; it can support e4 later.",
          10: "5...Qb6 attacks b2.",
          11: "6.Qb3 defends b2 and offers the queen trade: after ...Qxb3 axb3 our rook uses the half-open a-file.",
          12: "Black keeps the queens on and opens the f8 bishop.",
          13: "7.Ngf3 develops.",
          14: "Black develops.",
          15: "8.Be2 develops calmly and prepares castling.",
          16: "Black develops.",
          17: "9.O-O.",
          18: "Black castles.",
          19: "10.Qc2 steps out of the queen trade and eyes h7. Next come Ne5, or dxc5 followed by e4.",
        },
      },
      {
        id: "w-london-kid",
        name: "vs the King's Indian set-up (...g6, ...d6, ...e5)",
        moves: "d4 Nf6 Bf4 g6 e3 Bg7 Nf3 d6 h3 O-O Be2 Nbd7 O-O Qe8 c4 e5 Bh2",
        notes: {
          1: "1.d4 takes the centre.",
          2: "1...Nf6 keeps Black's options open.",
          3: "2.Bf4, the London set-up again.",
          4: "Black plans a King's Indian fianchetto.",
          5: "3.e3 supports d4.",
          6: "The bishop goes to the long diagonal.",
          7: "4.Nf3 develops and controls e5.",
          8: "4...d6 prepares ...e5 to hit our bishop.",
          9: "5.h3 gives the bishop a safe retreat on h2 and stops ...Ng4 and ...Bg4.",
          10: "Black castles.",
          11: "6.Be2 is modest but solid against the King's Indian.",
          12: "Black prepares ...e5.",
          13: "7.O-O.",
          14: "7...Qe8 prepares ...e5. Without it, ...e5 would lose a pawn to dxe5 dxe5 Nxe5.",
          15: "8.c4 grabs queenside space, so we have play on both wings.",
          16: "Black finally plays ...e5.",
          17: "9.Bh2 keeps the bishop, which now pressures e5. White continues with Nc3 and b4-b5, playing on the queenside where we have more space.",
        },
      },
    ],
  },
];
