import type { Unit } from '../types';

export const endgameTechnique: Unit = {
  id: 'endgame-technique',
  title: 'Endgame Technique',
  tagline: 'Activate your king, master the key pawn and rook endings, and convert won positions without stalemate accidents.',
  level: 'Intermediate',
  lessons: [
    // ---------------------------------------------------------------------------------------------
    {
      id: 'end-king-activity',
      title: 'The Active King',
      summary: 'In the endgame the king stops hiding and becomes one of your strongest pieces.',
      minutes: 12,
      steps: [
        {
          kind: 'read',
          title: 'A new role for the king',
          text: 'In the middlegame the king hides behind its pawns, because the enemy queen and rooks can mate it. Once the queens are off, that danger mostly disappears.\n\nIn the endgame the king is a strong piece that attacks pawns, escorts passed pawns and stops enemy ones. Very often the side whose king reaches the center first wins.',
        },
        {
          kind: 'read',
          title: 'Endgame principles',
          text: 'Guidelines that decide most endgames:\n- **Activate the king**: bring it toward the center or the pawns, early.\n- **Passed pawns must be pushed**, and enemy passed pawns must be stopped.\n- **Rooks belong on open files** and behind passed pawns.\n- When ahead in material, **trade pieces, not pawns**.\n- **Do not hurry**: improve your position before committing.\n\nHere White\'s king on d4 is already central, while Black\'s is still on g8.',
          fen: '6k1/5ppp/8/8/3K4/8/5PPP/8 w - - 0 1',
          marks: [
            { square: 'd4', color: 'green' },
            { square: 'g8', color: 'red' },
          ],
        },
        {
          kind: 'quiz',
          title: 'First things first',
          text: 'The queens have just been traded in a quiet position. What is usually your first priority?',
          choices: [
            {
              text: 'Bring the king toward the center.',
              correct: true,
              why: 'With the queens gone the king is safe to come out, and every move it makes toward the center makes it more useful.',
            },
            {
              text: 'Keep the king on g1 behind its pawns.',
              why: 'That is middlegame thinking. In the endgame a passive king is one of the most common reasons for losing.',
            },
            {
              text: 'Push the kingside pawns forward as fast as possible.',
              why: 'Pawn moves cannot be taken back and create weaknesses. Activate the king first, then decide on pawn moves.',
            },
          ],
        },
        {
          kind: 'move',
          title: 'Go after the pawns',
          text: 'Pawns are even and both kings stand in the center, but White\'s is closer to Black\'s weak queenside pawns. Find the only winning move.',
          fen: '8/4k3/1p4p1/p6p/P1K4P/1P4P1/8/8 w - - 0 1',
          solution: ['Kb5'],
          hint: 'The pawn on b6 has no defender. Go and get it.',
          success: '1.Kb5! Kd6 2.Kxb6 Kd5 3.Kxa5 and White\'s queenside pawns decide. Black\'s king is too slow to do the same on the kingside.',
        },
        {
          kind: 'move',
          title: 'Break in',
          text: 'Same pawns, different kings. Black\'s king guards the queenside for now. Find the only move that lets White\'s king break through.',
          fen: '8/3k4/1p4p1/p6p/P2K3P/1P4P1/8/8 w - - 0 1',
          solution: ['Kd5'],
          hint: 'Put your king directly opposite Black\'s king, with one square between them.',
          success: '1.Kd5! takes the **opposition**. Black\'s king must give way, and after 1...Ke7 2.Kc6 White wins the b6-pawn. Any other move lets Black hold the line.',
        },
        {
          kind: 'read',
          title: 'The Réti study',
          text: 'Richard Réti composed this study in 1921, and it still surprises strong players. White\'s king on h8 seems hopelessly far from Black\'s h-pawn, and Black\'s king will soon take the c6-pawn.\n\nThe secret: a king moving diagonally reaches two places at once. It can chase the h-pawn and head for its own pawn at the same time.',
          fen: '7K/8/k1P5/7p/8/8/8/8 w - - 0 1',
          arrows: [
            { from: 'h8', to: 'e5', color: 'green' },
            { from: 'h5', to: 'h1', color: 'red' },
          ],
        },
        {
          kind: 'move',
          title: 'Two targets at once',
          text: 'White to play and draw. Only one move works.',
          fen: '7K/8/k1P5/7p/8/8/8/8 w - - 0 1',
          solution: ['Kg7'],
          hint: 'Move diagonally toward the center: toward the h-pawn and toward c6 at the same time.',
          success: '1.Kg7! Every other move loses. Now watch why Black cannot win.',
        },
        {
          kind: 'demo',
          title: 'Réti\'s idea',
          text: 'Black can chase the c-pawn or run with the h-pawn, but not both.',
          fen: '8/6K1/k1P5/7p/8/8/8/8 b - - 1 1',
          moves: ['h4', 'Kf6', 'Kb6', 'Ke5', 'h3', 'Kd6', 'h2', 'c7', 'Kb7', 'Kd7', 'h1=Q', 'c8=Q+'],
          notes: [
            '1...h4 runs.',
            '2.Kf6 keeps approaching both targets.',
            '2...Kb6 goes for c6.',
            '3.Ke5! If 3...Kxc6, 4.Kf4 catches the h-pawn.',
            '3...h3 races on.',
            '4.Kd6 now supports the c-pawn.',
            '4...h2.',
            '5.c7 Kb7 6.Kd7 and both sides promote.',
            '5...Kb7.',
            '6.Kd7.',
            '6...h1=Q.',
            '7.c8=Q+ and the game is a draw. White\'s king did two jobs at once.',
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Once the queens are off, bring your king to the center.\n- An active king attacks weak pawns and escorts passed pawns.\n- Taking the opposition lets your king break through.\n- A king moving diagonally can pursue two goals at once.\n- Count moves: in king races, one tempo decides.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'end-king-pawn',
      title: 'King and Pawn vs King',
      summary: 'The rule of the square, key squares and the opposition: the foundation of every pawn ending.',
      minutes: 14,
      steps: [
        {
          kind: 'read',
          title: 'The rule of the square',
          text: 'Can the lone king catch a passed pawn? Draw a square with one side running from the pawn to its promotion square. If the defending king can step into that square on its move, it catches the pawn.\n\nHere the square of the a4-pawn is a4-e4-e8-a8. Black\'s king on f5 is one step outside it. Whoever moves first decides the race.',
          fen: '8/8/8/5k2/P7/8/8/7K w - - 0 1',
          marks: [
            { square: 'a4', color: 'blue' },
            { square: 'e4', color: 'blue' },
            { square: 'e8', color: 'blue' },
            { square: 'a8', color: 'blue' },
          ],
        },
        {
          kind: 'move',
          title: 'Win the race',
          text: 'White to move. White\'s king is far away, so the pawn must do it alone.',
          fen: '8/8/8/5k2/P7/8/8/7K w - - 0 1',
          solution: ['a5'],
          hint: 'Push the pawn, so that its square shrinks before Black\'s king can enter it.',
          success: '1.a5! The new square is a5-d5-d8-a8, and Black\'s king cannot reach it in one move. The pawn promotes.',
        },
        {
          kind: 'quiz',
          title: 'Black to move',
          text: 'Same position, but Black is to move. What happens?',
          fen: '8/8/8/5k2/P7/8/8/7K b - - 0 1',
          choices: [
            {
              text: 'Black steps into the square with ...Ke5, ...Ke4 or ...Ke6 and catches the pawn.',
              correct: true,
              why: 'The square is a4-e4-e8-a8. Any king move to the e-file enters it, and from then on the king keeps pace with the pawn.',
            },
            {
              text: 'The pawn promotes anyway.',
              why: 'Count it out: after 1...Ke5 2.a5 Kd6 3.a6 Kc7 the king arrives in time.',
            },
            {
              text: 'Black must attack White\'s king instead.',
              why: 'White\'s king is irrelevant here. Catching the pawn is all that matters.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Key squares',
          text: 'When the kings are near the pawn, think in **key squares**. If the attacking king reaches a key square, the pawn promotes whoever is to move.\n\nFor a pawn on its 2nd, 3rd or 4th rank the key squares are the three squares two ranks in front of it. For the e4-pawn they are d6, e6 and f6. Rook pawns are an exception, as you will see.',
          fen: '4k3/8/8/8/4P3/8/8/4K3 w - - 0 1',
          marks: [
            { square: 'd6', color: 'green' },
            { square: 'e6', color: 'green' },
            { square: 'f6', color: 'green' },
          ],
        },
        {
          kind: 'move',
          title: 'Reach a key square',
          text: 'The key squares of the e3-pawn are d5, e5 and f5. White to move and win.',
          fen: '8/4k3/8/8/4K3/4P3/8/8 w - - 0 1',
          solution: ['Ke5'],
          accept: ['Kd5', 'Kf5'],
          hint: 'The king goes first. The pawn can wait.',
          success: 'The king stands on a key square, so the win is guaranteed however Black defends. A timid move such as 1.Kf3? would let Black\'s king come forward and draw.',
        },
        {
          kind: 'read',
          title: 'The opposition',
          text: 'Kings **in opposition** stand on the same file (or rank) with one square between them. The side that must move has to give way.\n\nHere White has just played Ke5 and it is Black to move: Black must step aside, and White\'s king walks to d6 or f6, two key squares. Taking the opposition is how a king fights its way to a key square.',
          fen: '8/4k3/8/4K3/4P3/8/8/8 b - - 1 1',
          lastMove: ['f5', 'e5'],
          marks: [
            { square: 'e5', color: 'green' },
            { square: 'e7', color: 'yellow' },
          ],
        },
        {
          kind: 'move',
          title: 'Take the opposition',
          text: 'White to move and win. Only one move does it: the natural 1.e5? only draws.',
          fen: '8/4k3/8/5K2/4P3/8/8/8 w - - 0 1',
          solution: ['Ke5'],
          hint: 'Put your king directly in front of Black\'s king, with one square between them.',
          success: '1.Ke5! and Black must give way. See the rest of the technique next.',
        },
        {
          kind: 'demo',
          title: 'Converting the win',
          text: 'From the opposition, the king escorts the pawn home. Note that White\'s king stays in front of the pawn until the very end.',
          fen: '8/4k3/8/4K3/4P3/8/8/8 b - - 1 1',
          moves: ['Kd7', 'Kf6', 'Ke8', 'e5', 'Kf8', 'e6', 'Ke8', 'e7', 'Kd7', 'Kf7'],
          notes: [
            '1...Kd7 gives way on one side.',
            '2.Kf6 reaches a key square.',
            '2...Ke8.',
            '3.e5: now the pawn advances under the king\'s protection.',
            '3...Kf8 takes the opposition, but White\'s pawn still has spare moves.',
            '4.e6: with the king on the sixth rank next to its pawn, the rest is easy.',
            '4...Ke8.',
            '5.e7.',
            '5...Kd7.',
            '6.Kf7 and the pawn promotes.',
          ],
        },
        {
          kind: 'move',
          title: 'Defend with the opposition',
          text: 'Now you defend. Black to move: only one move draws.',
          fen: '8/8/8/4k3/8/3KP3/8/8 b - - 0 1',
          solution: ['Kd5'],
          hint: 'Stand directly opposite White\'s king.',
          success: '1...Kd5! takes the opposition and keeps White\'s king away from d5, e5 and f5, the key squares of the e3-pawn. After 2.e4+ Ke6 Black keeps answering with the opposition and draws.',
        },
        {
          kind: 'read',
          title: 'The rook-pawn exception',
          text: 'With a rook pawn the defender only needs to reach the corner in front of it. White\'s king cannot get round, and the attacker runs into stalemate.\n\nHere, 1...Kb8 2.a7+ Ka8 3.Ka6 is stalemate. When you are ahead with an a- or h-pawn, keep the enemy king out of the corner; when you are behind, run for it.',
          fen: 'k7/8/PK6/8/8/8/8/8 b - - 0 1',
          marks: [{ square: 'a8', color: 'yellow' }],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Rule of the square: can the king step into the pawn\'s square?\n- Key squares: if your king reaches one, the pawn promotes.\n- Bring the king first, push the pawn later.\n- The opposition decides who reaches the key squares.\n- A king on the sixth rank in front of its pawn always wins, except with a rook pawn.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'end-pawn-weapons',
      title: 'Pawn Endgame Weapons',
      summary: 'The outside passed pawn, the protected passer, the breakthrough and triangulation.',
      minutes: 15,
      steps: [
        {
          kind: 'read',
          title: 'More than king and pawn',
          text: 'With several pawns each, material is often equal, yet one side wins. The difference is usually one of four weapons:\n- an **outside passed pawn** that pulls the enemy king away\n- a **protected passed pawn** that the enemy king can never take\n- a **breakthrough** that turns a pawn majority into a queen\n- **triangulation**, a king manoeuvre that hands the move to the opponent',
        },
        {
          kind: 'read',
          title: 'The outside passed pawn',
          text: 'Pawns are equal, and both sides have a passed pawn. White\'s a-pawn is far from the kings, Black\'s e-pawn is next to them.\n\nThat makes all the difference. Black\'s king must run to the a-file to stop the a-pawn, while White\'s king eats the e-pawn and then the kingside. An outside passer works as a **decoy**.',
          fen: '8/6pp/8/3kp3/P7/3K4/6PP/8 w - - 0 1',
          marks: [
            { square: 'a4', color: 'green' },
            { square: 'e5', color: 'red' },
          ],
        },
        {
          kind: 'demo',
          title: 'The decoy at work',
          text: 'Watch the two kings go in opposite directions. White\'s king has the better target.',
          fen: '8/6pp/8/3kp3/P7/3K4/6PP/8 w - - 0 1',
          moves: ['a5', 'Kc6', 'Ke4', 'Kb5', 'Kxe5', 'Kxa5', 'Ke6', 'Kb6', 'Kf7', 'g5', 'Kg7', 'h5', 'Kh6', 'h4', 'Kxg5'],
          notes: [
            '1.a5 drags Black\'s king toward the corner.',
            '1...Kc6 must chase it.',
            '2.Ke4 heads for e5.',
            '2...Kb5.',
            '3.Kxe5 wins Black\'s passed pawn.',
            '3...Kxa5 wins White\'s, but Black\'s king is now far offside.',
            '4.Ke6 heads for the kingside pawns.',
            '4...Kb6.',
            '5.Kf7.',
            '5...g5.',
            '6.Kg7.',
            '6...h5.',
            '7.Kh6.',
            '7...h4.',
            '8.Kxg5 and White\'s last pawns promote long before Black\'s king returns.',
          ],
        },
        {
          kind: 'move',
          title: 'Use the outside passer',
          text: 'Pawns are even: White has a passed a-pawn far from the action, Black has three pawns against two on the kingside. Find the move that wins at once.',
          fen: '8/5ppp/5k2/8/P7/8/3K2PP/8 w - - 0 1',
          solution: ['a5'],
          hint: 'Check the square of the a-pawn after it advances.',
          success: '1.a5! Black\'s king cannot enter the square a5-d5-d8-a8, so the pawn promotes. King moves keep an edge but let Black\'s king come back. The farther a passed pawn is from the enemy king, the stronger it is.',
        },
        {
          kind: 'read',
          title: 'The protected passed pawn',
          text: 'White\'s b5-pawn is passed and protected by the a4-pawn. Black\'s king can never capture it, so it must stay near the b-pawn to stop it from promoting.\n\nWhite\'s king, in contrast, is free. It can walk to the kingside and eat the g- and h-pawns, or win the a5-pawn. A protected passer ties the enemy king down while yours goes shopping.',
          fen: '8/8/1k4p1/pP5p/P2K3P/6P1/8/8 w - - 0 1',
          marks: [
            { square: 'b5', color: 'green' },
            { square: 'b6', color: 'red' },
          ],
          arrows: [{ from: 'a4', to: 'b5', color: 'green' }],
        },
        {
          kind: 'move',
          title: 'The breakthrough',
          text: 'Three pawns against three, and the kings are far away. White to play and make a queen.',
          fen: '6k1/ppp5/8/PPP5/8/8/8/6K1 w - - 0 1',
          solution: ['b6'],
          hint: 'Sacrifice the middle pawn.',
          success: '1.b6! If 1...axb6 2.c6! bxc6 3.a6 and the a-pawn promotes. If 1...cxb6 2.a6! bxa6 3.c6. Two sacrifices clear the way for the third pawn.',
        },
        {
          kind: 'demo',
          title: 'How the breakthrough works',
          text: 'Here is the line after 1...cxb6. Every capture opens a file for another white pawn.',
          fen: '6k1/ppp5/8/PPP5/8/8/8/6K1 w - - 0 1',
          moves: ['b6', 'cxb6', 'a6', 'bxa6', 'c6', 'Kf7', 'c7', 'Ke7', 'c8=Q'],
          notes: [
            '1.b6! offers the middle pawn.',
            '1...cxb6.',
            '2.a6! offers a second pawn.',
            '2...bxa6.',
            '3.c6: nothing can stop this pawn.',
            '3...Kf7.',
            '4.c7.',
            '4...Ke7.',
            '5.c8=Q. Black\'s king was simply too far away.',
          ],
        },
        {
          kind: 'move',
          title: 'Your turn, on the kingside',
          text: 'Black to move. The same three-against-three pattern, on the other wing and with the other colour. Break through.',
          fen: '1k6/8/8/8/5ppp/8/5PPP/1K6 b - - 0 1',
          solution: ['g3'],
          hint: 'Again, sacrifice the middle pawn first.',
          success: '1...g3! If 2.hxg3 f3!, and if 2.fxg3 h3!: in both cases a black pawn runs through, and White\'s king is far too slow. Careful: after 2.fxg3, the tempting 2...hxg3? lets White\'s g2-pawn block the last pawn.',
        },
        {
          kind: 'read',
          title: 'Zugzwang and triangulation',
          text: 'A **mutual zugzwang**: whoever moves loses ground. With Black to move, the king must leave c7 and White\'s king breaks in to win e6. With White to move, Black holds by mirroring every step of White\'s king.\n\nIf the defending king had only two squares to shuttle between, White could **triangulate**: walk around three squares while Black goes back and forth, and reach this position with Black to move. Here Black\'s king has room, so it mirrors and draws.',
          fen: '8/2k5/4p3/2KpP3/3P4/8/8/8 w - - 0 1',
          marks: [
            { square: 'c5', color: 'green' },
            { square: 'c7', color: 'red' },
          ],
        },
        {
          kind: 'quiz',
          title: 'What triangulation does',
          text: 'What is the purpose of triangulation?',
          choices: [
            {
              text: 'To reach the same position with the opponent to move.',
              correct: true,
              why: 'Three king moves around a triangle against the opponent\'s two back-and-forth moves hand over the move in a mutual zugzwang.',
            },
            {
              text: 'To attack three enemy pawns at once.',
              why: 'Triangulation is about tempo, not targets. The king returns to where it started.',
            },
            {
              text: 'To avoid stalemate.',
              why: 'It is a way to win a zugzwang battle, not a stalemate trick.',
            },
          ],
        },
        {
          kind: 'quiz',
          title: 'Which weapon?',
          text: 'Pawns are even, and your only passed pawn is on the a-file, while all the other pawns and both kings are on the kingside. Which weapon do you have?',
          choices: [
            {
              text: 'An outside passed pawn: push it to drag the enemy king away, then win pawns on the other wing.',
              correct: true,
              why: 'The a-pawn is far from the action. The enemy king must go and stop it, leaving its own pawns undefended.',
            },
            {
              text: 'A breakthrough.',
              why: 'A breakthrough needs a pawn majority facing enemy pawns, usually three against three or two against one.',
            },
            {
              text: 'Nothing: equal pawns means a draw.',
              why: 'In pawn endings the position of the pawns matters far more than their number.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- An outside passed pawn is a decoy: push it, then win pawns on the other wing.\n- A protected passed pawn ties the enemy king down permanently.\n- With pawns facing each other, look for a breakthrough sacrifice.\n- Triangulation hands the move to your opponent when zugzwang decides.\n- In pawn endings count every tempo; there is no room for approximate moves.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'end-lucena-philidor',
      title: 'Lucena and Philidor',
      summary: 'The two rook-endgame positions every club player must know: how to win one and how to hold the other.',
      minutes: 15,
      steps: [
        {
          kind: 'read',
          title: 'Rook and pawn against rook',
          text: 'Rook endings are the most common endings in practice, and rook and pawn against rook is their core. Two positions answer most questions:\n- the **Lucena position**, where the attacker wins by **building a bridge**\n- the **Philidor position**, where the defender draws with the **third-rank defence**\n\nLearn both and you will know when to play for a win and how to save a draw.',
        },
        {
          kind: 'read',
          title: 'The Lucena position',
          text: 'White\'s pawn is on the seventh rank and the king stands on the promotion square. Black\'s king is cut off by the rook on the e-file, and Black\'s rook guards the c-file, so White\'s king cannot simply walk out.\n\nIf the king steps out, the black rook checks it from behind. The winning method is to prepare a shelter: White\'s rook will block the checks.',
          fen: '3K4/3P1k2/8/8/8/8/2r5/4R3 w - - 0 1',
          marks: [
            { square: 'd8', color: 'yellow' },
            { square: 'd7', color: 'yellow' },
          ],
          arrows: [{ from: 'e1', to: 'e8', color: 'blue' }],
        },
        {
          kind: 'demo',
          title: 'Building a bridge',
          text: 'The standard method: drive the black king one file further away, put the rook on the fourth rank, walk the king out, and block the last check with the rook.',
          fen: '3K4/3P1k2/8/8/8/8/2r5/4R3 w - - 0 1',
          moves: ['Rf1+', 'Kg7', 'Rf4', 'Rc1', 'Ke7', 'Re1+', 'Kd6', 'Rd1+', 'Ke6', 'Re1+', 'Kd5', 'Rd1+', 'Rd4'],
          notes: [
            '1.Rf1+ pushes Black\'s king away from the e-file.',
            '1...Kg7.',
            '2.Rf4! The rook goes to the fourth rank. This is the "bridge" in the making.',
            '2...Rc1 waits.',
            '3.Ke7: the king finally comes out.',
            '3...Re1+ starts checking.',
            '4.Kd6 heads down the board toward the rook on the fourth rank.',
            '4...Rd1+.',
            '5.Ke6.',
            '5...Re1+.',
            '6.Kd5.',
            '6...Rd1+.',
            '7.Rd4! blocks the check. The bridge is built, the checks are over and the pawn promotes.',
          ],
        },
        {
          kind: 'move',
          title: 'Complete the bridge',
          text: 'Black has just checked from d1. End the checks for good.',
          fen: '8/3P2k1/8/3K4/5R2/8/8/3r4 w - - 12 7',
          solution: ['Rd4'],
          hint: 'Block the check with the rook, which is protected by the king.',
          success: '7.Rd4! The rook shields the king, the checks are over, and d8=Q follows.',
        },
        {
          kind: 'quiz',
          title: 'Why the fourth rank?',
          text: 'In the Lucena position, why does White put the rook on the fourth rank (Rf4) before bringing the king out?',
          choices: [
            {
              text: 'So the rook can later block a check on the d-file while protected by the king.',
              correct: true,
              why: 'The king walks down to d5, and the rook on the fourth rank arrives on d4 to block the check with support. That is the bridge.',
            },
            {
              text: 'To attack Black\'s king.',
              why: 'The rook is not attacking the king; its job is to shelter White\'s own king from checks.',
            },
            {
              text: 'To stop Black\'s rook from reaching the first rank.',
              why: 'Black\'s rook can still move freely along the first rank. The point is shelter, not restriction.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'The Philidor position',
          text: 'The defender\'s king stands on the promotion square. White\'s pawn and king have reached the fifth rank.\n\nBlack\'s rook sits on the sixth rank (Black\'s **third rank**, hence the name), so White\'s king cannot advance to the sixth rank without being checked. White\'s only try is to push the pawn to e6, but then the king loses its shelter and Black checks it from behind.',
          fen: '4k3/7R/1r6/4PK2/8/8/8/8 w - - 1 2',
          arrows: [{ from: 'b6', to: 'h6', color: 'green' }],
          marks: [{ square: 'e8', color: 'yellow' }],
        },
        {
          kind: 'move',
          title: 'Take up the Philidor',
          text: 'Black to move. White threatens Kf6 with mating ideas on the back rank. Set up the Philidor defence: where does your rook belong?',
          fen: '1r2k3/7R/8/4PK2/8/8/8/8 b - - 0 1',
          solution: ['Rb6'],
          hint: 'Put your rook on the rank in front of White\'s king.',
          success: '1...Rb6! White\'s king cannot go to the sixth rank. A passive rook on the back rank would lose after Kf6.',
        },
        {
          kind: 'move',
          title: 'Now check from behind',
          text: 'White pushed e6 and played Kf6, threatening Rh8#. The pawn no longer shields the king. Black to move and draw.',
          fen: '4k3/7R/4PK2/8/8/8/8/1r6 b - - 2 3',
          solution: ['Rf1+'],
          hint: 'Check from a distance, along the file.',
          success: '3...Rf1+! The king has nowhere to hide: it cannot use the e-pawn as a shield, and the checks continue forever. Draw.',
        },
        {
          kind: 'demo',
          title: 'The Philidor defence in full',
          text: 'The whole method in one line.',
          fen: '1r2k3/7R/8/4PK2/8/8/8/8 b - - 0 1',
          moves: ['Rb6', 'e6', 'Rb1', 'Kf6', 'Rf1+', 'Ke5', 'Re1+', 'Kd6', 'Rd1+', 'Ke5', 'Re1+'],
          notes: [
            '1...Rb6: the third-rank defence.',
            '2.e6 is the only try to make progress.',
            '2...Rb1! Now the rook goes to the other end of the board.',
            '3.Kf6 threatens mate.',
            '3...Rf1+ and the checks begin.',
            '4.Ke5.',
            '4...Re1+.',
            '5.Kd6.',
            '5...Rd1+.',
            '6.Ke5.',
            '6...Re1+ and White cannot escape the checks. Draw.',
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Lucena (pawn on the seventh, king in front): drive the enemy king away, rook to the fourth rank, king out, block the last check.\n- Philidor (defending king in front of the pawn): rook on the third rank until the pawn advances.\n- Once the pawn reaches the sixth, drop the rook to the far end and check from behind.\n- A passive rook on the back rank usually loses.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'end-rook-activity',
      title: 'Active Rooks',
      summary: 'Rooks behind passed pawns, cutting off the enemy king, and why passive rooks lose.',
      minutes: 13,
      steps: [
        {
          kind: 'read',
          title: 'Rooks need air',
          text: 'In rook endings activity is often worth more than a pawn. An active rook attacks pawns, cuts off the enemy king and supports its own passed pawns. A passive rook just defends and waits to be outplayed.\n\nThree rules of thumb:\n- Put rooks **behind passed pawns**, yours and your opponent\'s.\n- **Cut off the enemy king** from the pawns with your rook.\n- A rook on the **seventh rank** attacks pawns and confines the king.',
        },
        {
          kind: 'read',
          title: 'Behind the passed pawn',
          text: 'Tarrasch\'s rule: rooks belong behind passed pawns. White\'s rook on a1 gains scope with every step the pawn takes. Black\'s rook on a8, in front of the pawn, loses scope with every step and ends up tied to the corner.\n\nWhite\'s king is then free to walk to the queenside, while Black\'s rook can only watch.',
          fen: 'r7/5pk1/6p1/P6p/7P/6P1/5PK1/R7 w - - 0 1',
          arrows: [{ from: 'a1', to: 'a5', color: 'green' }],
          marks: [{ square: 'a8', color: 'red' }],
        },
        {
          kind: 'quiz',
          title: 'Why behind?',
          text: 'Why is a rook behind its own passed pawn stronger than a rook in front of it?',
          choices: [
            {
              text: 'As the pawn advances, the rook behind it controls more squares, while a rook in front gets boxed in.',
              correct: true,
              why: 'A rook behind the pawn keeps supporting it all the way to the promotion square, and its file only grows longer.',
            },
            {
              text: 'Because the rook in front blocks the pawn\'s path to promotion.',
              why: 'Partly true, but the main point is activity: the rook in front loses squares and becomes passive.',
            },
            {
              text: 'Because the rook behind can protect the king.',
              why: 'King safety has little to do with it. The point is the scope of the rook.',
            },
          ],
        },
        {
          kind: 'move',
          title: 'Cut off the king',
          text: 'White\'s king and pawn want to advance, and Black\'s king is heading back. Cut it off as far away as possible. Only one move wins.',
          fen: 'r7/8/6k1/8/3P4/3K4/8/7R w - - 0 1',
          solution: ['Rf1'],
          hint: 'Keep Black\'s king two files away from the pawn.',
          success: '1.Rf1! Black\'s king is confined to the g- and h-files, two files away from the d-pawn. White\'s king and pawn advance together and win. 1.Re1? only cuts it off by one file and lets Black draw.',
        },
        {
          kind: 'read',
          title: 'One file is not enough',
          text: 'Here Black\'s king is already on the f-file. After 1.Re1 it is cut off by only one file, gets back in time to fight the pawn, and Black holds the draw.\n\nThe lesson: cut off the defending king early, and by as many files as possible. In positions like these, a two-file cut-off wins and a one-file cut-off lets the defender hold.',
          fen: 'r7/8/5k2/8/3P4/3K4/8/7R w - - 0 1',
          arrows: [{ from: 'h1', to: 'e1', color: 'blue' }],
          marks: [{ square: 'f6', color: 'yellow' }],
        },
        {
          kind: 'move',
          title: 'Defend: race back',
          text: 'Now defend. Black to move in the position from the winning example. Stop White from cutting off your king.',
          fen: 'r7/8/6k1/8/3P4/3K4/8/7R b - - 0 1',
          solution: ['Kf6'],
          accept: ['Kf5', 'Kf7'],
          hint: 'Get your king to the f-file before White\'s rook arrives there.',
          success: 'The king reaches the f-file in time. Now White can cut it off by only one file, and Black draws. In rook endings a single tempo often decides.',
        },
        {
          kind: 'move',
          title: 'Cut off along the rank',
          text: 'Black has a dangerous passed a-pawn. Passive defence loses. Find the rook move that keeps Black\'s king away from its pawn.',
          fen: '3R4/5pk1/6p1/7p/pr5P/6P1/5PK1/8 w - - 0 1',
          solution: ['Rd6'],
          hint: 'Rooks cut off kings along ranks as well as files. Black\'s king wants to walk to the queenside.',
          success: '1.Rd6! cuts Black\'s king off along the sixth rank. Next come Rd7 and Ra7, behind the passed pawn. The passive 1.Ra8? lets Black\'s king walk over to support the pawn, and White should lose.',
        },
        {
          kind: 'read',
          title: 'The seventh rank',
          text: 'A rook on the seventh rank attacks the pawns that are still on their starting squares and keeps the enemy king on the back rank.\n\nHere 1.Rc7 hits b7 at once. Black\'s rook must defend passively, and White\'s king walks up to support the attack. That is the same idea as a rook on an open file in the middlegame, one step further.',
          fen: 'r5k1/1p3ppp/p7/8/8/1P6/P4PPP/2R3K1 w - - 0 1',
          arrows: [{ from: 'c1', to: 'c7', color: 'green' }],
          marks: [{ square: 'b7', color: 'red' }],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Rooks belong behind passed pawns, yours and your opponent\'s.\n- Cut off the enemy king from the pawn, by two files if you can.\n- As the defender, race your king back before it is cut off.\n- Rooks cut off kings along ranks too.\n- An active rook is often worth a pawn; a passive one often loses.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'end-basic-mates',
      title: 'Basic Mates Without Mistakes',
      summary: 'Mate with king and queen or king and rook quickly, by method, and never stalemate.',
      minutes: 13,
      steps: [
        {
          kind: 'read',
          title: 'Why method matters',
          text: 'King and queen, or king and rook, against a lone king is a forced win. Yet players regularly draw these positions by **stalemate** or run into the **50-move rule**.\n\nThe cure is a method. With the queen, mate takes at most ten moves; with the rook, at most sixteen. Both methods do the same thing: drive the king to the edge, then bring your own king to help mate it.',
        },
        {
          kind: 'read',
          title: 'Queen: the knight\'s-move trick',
          text: 'Place the queen a knight\'s move away from the enemy king. The king is then boxed in by the queen\'s lines. Each time the king moves, move the queen to keep the knight\'s-move distance, and the box shrinks.\n\nOnce the king is on the edge, stop chasing. Leave it two squares, and bring your own king up to support the mate.',
          fen: '8/3k4/8/2Q5/8/8/8/3K4 w - - 0 1',
          marks: [
            { square: 'c5', color: 'green' },
            { square: 'd7', color: 'red' },
          ],
        },
        {
          kind: 'demo',
          title: 'Queen mate by method',
          text: 'The queen shepherds the king to the corner with knight\'s-move steps, then White\'s king walks up.',
          fen: '8/3k4/8/2Q5/8/8/8/3K4 w - - 0 1',
          moves: ['Qb6', 'Ke7', 'Qc6', 'Kf7', 'Qd6', 'Kg7', 'Qe6', 'Kh7', 'Qf6', 'Kg8', 'Qe7', 'Kh8', 'Ke2', 'Kg8', 'Kf3', 'Kh8', 'Kg4', 'Kg8', 'Kg5', 'Kh8', 'Kg6', 'Kg8', 'Qg7#'],
          notes: [
            '1.Qb6: the king is confined to the seventh and eighth ranks.',
            '1...Ke7.',
            '2.Qc6, again a knight\'s move away.',
            '2...Kf7.',
            '3.Qd6.',
            '3...Kg7.',
            '4.Qe6.',
            '4...Kh7.',
            '5.Qf6.',
            '5...Kg8.',
            '6.Qe7! The king is on the edge with two squares, g8 and h8. Stop chasing.',
            '6...Kh8.',
            '7.Ke2: now the king walks up.',
            '7...Kg8.',
            '8.Kf3.',
            '8...Kh8.',
            '9.Kg4.',
            '9...Kg8.',
            '10.Kg5.',
            '10...Kh8.',
            '11.Kg6.',
            '11...Kg8.',
            '12.Qg7#, the queen protected by the king.',
          ],
        },
        {
          kind: 'move',
          title: 'Mate, don\'t stalemate',
          text: 'White to move. Two natural-looking queen moves stalemate. Deliver mate instead.',
          fen: 'k7/8/1K2Q3/8/8/8/8/8 w - - 0 1',
          solution: ['Qc8#'],
          hint: 'Check along the back rank. White\'s king already covers a7 and b7.',
          success: 'Mate. Qe8# and Qg8# work too. But 1.Qd6?? or 1.Qe5?? would take b8 away without giving check: stalemate, and half a point thrown away.',
        },
        {
          kind: 'quiz',
          title: 'Bring the king',
          text: 'Black\'s king is trapped on a8 and a7. What is White\'s best move?',
          fen: 'k7/8/8/3K4/8/8/8/1Q6 w - - 0 1',
          choices: [
            {
              text: '1.Kc6',
              correct: true,
              why: 'The queen has done her job. After 1...Ka7 2.Qb7# the king supports the mate. The queen alone can never mate.',
            },
            {
              text: '1.Qb6',
              why: 'Stalemate! Black\'s king has no legal move and is not in check.',
            },
            {
              text: '1.Qb4',
              why: 'Not a blunder, but it only waits. The king still has to come, so bring it now.',
            },
          ],
        },
        {
          kind: 'move',
          title: 'Mate in the other corner',
          text: 'White to move. Again one careless move stalemates. Find a mate.',
          fen: '7k/5K2/8/8/8/5Q2/8/8 w - - 0 1',
          solution: ['Qh5#'],
          hint: 'The king covers g7 and g8. Check along the h-file.',
          success: 'Mate. Qh3# and Qh1# also work. 1.Qf5?? would cover h7 without check: stalemate.',
        },
        {
          kind: 'read',
          title: 'Rook: the shrinking box',
          text: 'The rook cuts the enemy king off along a rank or file, forming a **box**. Your king approaches; when the kings stand **in opposition**, a rook check pushes the enemy king back a rank.\n\nWhen the enemy king steps away from the opposition instead, make a **waiting move** with the rook, keeping the box closed. Sooner or later the king must step into the opposition, and the rook checks again, finally with mate on the edge.',
          fen: '8/8/4k3/7R/4K3/8/8/8 w - - 0 1',
          arrows: [{ from: 'h5', to: 'a5', color: 'blue' }],
          marks: [
            { square: 'e4', color: 'green' },
            { square: 'e6', color: 'red' },
          ],
        },
        {
          kind: 'demo',
          title: 'Rook mate by method',
          text: 'Checks when the kings face each other, king moves otherwise, and one waiting move at the end.',
          fen: '8/8/4k3/7R/4K3/8/8/8 w - - 0 1',
          moves: ['Rh6+', 'Kd7', 'Ke5', 'Ke7', 'Rh7+', 'Kd8', 'Kd6', 'Ke8', 'Ke6', 'Kf8', 'Kf6', 'Kg8', 'Kg6', 'Kf8', 'Ra7', 'Kg8', 'Ra8#'],
          notes: [
            '1.Rh6+: the kings were in opposition, so the check pushes Black back.',
            '1...Kd7.',
            '2.Ke5 follows.',
            '2...Ke7 takes the opposition.',
            '3.Rh7+ and Black is on the edge.',
            '3...Kd8.',
            '4.Kd6 takes the opposition. Mate is threatened.',
            '4...Ke8 steps away.',
            '5.Ke6.',
            '5...Kf8.',
            '6.Kf6.',
            '6...Kg8.',
            '7.Kg6.',
            '7...Kf8.',
            '8.Ra7! A waiting move: the box stays closed.',
            '8...Kg8 is forced into the opposition.',
            '9.Ra8#.',
          ],
        },
        {
          kind: 'quiz',
          title: 'Force the opposition',
          text: 'Black\'s king is on the edge but can still slip toward the c-file. White has mate in two. What is the first move?',
          fen: '3k4/8/4K3/8/8/8/8/7R w - - 0 1',
          choices: [
            {
              text: '1.Rc1',
              correct: true,
              why: 'The rook takes away c7 and c8. Black\'s only move is 1...Ke8, straight into the opposition, and 2.Rc8# follows.',
            },
            {
              text: '1.Rh8+',
              why: 'The check comes too early: the kings are not in opposition, so the king escapes to c7.',
            },
            {
              text: '1.Kd6',
              why: 'It takes the opposition, but Black steps away with 1...Kc8 or 1...Ke8 and the chase continues. Mate comes later, not in two.',
            },
          ],
        },
        {
          kind: 'quiz',
          title: 'Spot the stalemate',
          text: 'White to move. Which of these moves is stalemate?',
          fen: 'k7/8/1K6/8/8/6Q1/8/8 w - - 0 1',
          choices: [
            {
              text: '1.Qc7',
              correct: true,
              why: 'Check square by square: a7 and b7 are covered by White\'s king, b8 and b7 by the queen. Black is not in check and has no legal move: stalemate.',
            },
            {
              text: '1.Qg8+',
              why: 'That is mate, not stalemate: the queen checks along the back rank and the king covers a7 and b7.',
            },
            {
              text: '1.Qf3+',
              why: 'A check along the long diagonal, but not mate and not stalemate: Black escapes with ...Kb8.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Queen: stay a knight\'s move away and shrink the box; stop when the king reaches the edge.\n- Rook: check when the kings are in opposition, otherwise move the king or make a waiting move.\n- Always bring your own king; neither piece can mate alone.\n- Before every move, ask: does my opponent still have a legal move?',
        },
      ],
    },
  ],
};
