import type { Unit } from '../types';

const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';

export const openingPlay: Unit = {
  id: 'opening-play',
  title: 'Opening Principles',
  tagline: 'Start every game with a plan: center, development, king safety, and the classic traps to spring and avoid.',
  level: 'Beginner',
  lessons: [
    // ---------------------------------------------------------------------------------------------
    {
      id: 'open-three-goals',
      title: 'The Three Opening Goals',
      summary: 'Fight for the center, develop your pieces and get your king to safety, in that spirit, from move one.',
      minutes: 12,
      steps: [
        {
          kind: 'read',
          title: 'Three jobs',
          text: 'Every sound opening does three jobs: it fights for the **center**, it **develops** the pieces, and it gets the **king to safety**, usually by castling.\n\nThe player who finishes these jobs first reaches the middlegame with more active pieces and fewer worries. Before each opening move, ask which of the three jobs it serves. Good moves often serve two at once.',
          fen: START,
          marks: [
            { square: 'd4', color: 'yellow' },
            { square: 'e4', color: 'yellow' },
            { square: 'd5', color: 'yellow' },
            { square: 'e5', color: 'yellow' },
          ],
        },
        {
          kind: 'read',
          title: 'Goal 1: the center',
          text: 'The squares d4, e4, d5 and e5 are the high ground. Pieces placed near them can reach either wing quickly, and pawns placed on them take space and push enemy pieces back.\n\nHere White has built the **ideal center** with pawns on e4 and d4. Together they cover c5, d5, e5 and f5, so Black\'s pieces have fewer good squares.',
          fen: 'rnbqkb1r/ppp1pppp/3p1n2/8/3PP3/2N5/PPP2PPP/R1BQKBNR b KQkq - 2 3',
          arrows: [
            { from: 'e4', to: 'd5', color: 'green' },
            { from: 'e4', to: 'f5', color: 'green' },
            { from: 'd4', to: 'c5', color: 'green' },
            { from: 'd4', to: 'e5', color: 'green' },
          ],
        },
        {
          kind: 'demo',
          title: 'A model opening',
          text: 'Watch both sides meet all three goals in the Italian Game. Notice that almost every move develops a piece, supports the center, or prepares castling.',
          fen: START,
          moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd3', 'd6', 'O-O', 'O-O'],
          notes: [
            '1.e4 claims central space and opens lines for the queen and the light-squared bishop.',
            '1...e5 stakes an equal claim in the center.',
            '2.Nf3 develops toward the center with a threat: the e5-pawn is attacked.',
            '2...Nc6 develops and defends e5 in one move.',
            '3.Bc4 puts the bishop on an active diagonal aimed at f7, the weakest point in Black\'s camp.',
            '3...Bc5 mirrors the idea and aims at f2.',
            '4.c3 prepares d4, to build a full pawn center later.',
            '4...Nf6 develops and attacks e4.',
            '5.d3 defends e4 and opens the c1-bishop.',
            '5...d6 supports e5 and opens the c8-bishop.',
            '6.O-O: the king is safe and the rook moves toward the center.',
            '6...O-O: both sides have met all three goals. The middlegame begins.',
          ],
        },
        {
          kind: 'read',
          title: 'Goal 2: development',
          text: 'Bring the **minor pieces** (knights and bishops) out first, toward the center. A knight on f3 covers d4 and e5; on h3 it would cover only edge squares.\n\nRules of thumb:\n- Move each piece once before you move any piece twice.\n- Knights usually come out before bishops.\n- Keep the queen at home until the minor pieces are out.\n- Every move should bring a new piece into play or support the center.',
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
          arrows: [
            { from: 'f3', to: 'e5', color: 'green' },
            { from: 'f3', to: 'd4', color: 'green' },
            { from: 'c6', to: 'd4', color: 'blue' },
            { from: 'c6', to: 'e5', color: 'blue' },
          ],
        },
        {
          kind: 'quiz',
          title: 'Choose a move',
          text: 'White to move after 1.e4 e5 2.Nf3 Nc6. Which move follows the opening principles best?',
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
          choices: [
            {
              text: '3.Bc4',
              correct: true,
              why: 'It develops a new piece to an active diagonal, eyes f7 and clears the way for castling.',
            },
            {
              text: '3.Qe2',
              why: 'The queen comes out early and blocks the f1-bishop. Develop the minor pieces first.',
            },
            {
              text: '3.h4',
              why: 'A flank pawn move that helps neither the center, nor development, nor king safety.',
            },
            {
              text: '3.Ng5',
              why: 'It moves the same piece twice and threatens nothing, because f7 is defended by the king. It simply loses time.',
            },
          ],
        },
        {
          kind: 'move',
          title: 'Develop with gain of time',
          text: 'After 1.e4 d5 2.exd5 Qxd5 Black\'s queen is already in the center. Develop a piece so that it attacks the queen and forces her to move again.',
          fen: 'rnb1kbnr/ppp1pppp/8/3q4/8/8/PPPP1PPP/RNBQKBNR w KQkq - 0 3',
          solution: ['Nc3'],
          hint: 'Which knight move attacks d5?',
          success: '3.Nc3 develops and hits the queen. Black must spend another move on her, while White adds another piece to the game. This is called gaining a **tempo**.',
        },
        {
          kind: 'read',
          title: 'Goal 3: king safety',
          text: 'In the center the king stands on the files that open first when pawns are exchanged. **Castling** tucks it behind a wall of pawns and brings a rook toward the center in a single move.\n\nCastle early, usually within the first ten moves, and avoid pushing the pawns in front of your castled king without a clear reason. When your opponent\'s king is stuck in the center, open lines against it.',
          fen: 'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2PP1N2/PP3PPP/RNBQ1RK1 w - - 2 7',
          marks: [
            { square: 'g1', color: 'green' },
            { square: 'g8', color: 'green' },
          ],
        },
        {
          kind: 'demo',
          title: 'Morphy\'s Opera Game, 1858',
          text: 'Paul Morphy played this game during a performance at the Paris Opera against the Duke of Brunswick and Count Isouard. Watch how fast development and a king left in the center decide the game.',
          fen: START,
          moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'Bg4', 'dxe5', 'Bxf3', 'Qxf3', 'dxe5', 'Bc4', 'Nf6', 'Qb3', 'Qe7', 'Nc3', 'c6', 'Bg5', 'b5'],
          notes: [
            'A classical start.',
            '2...d6, the Philidor Defence: solid but passive.',
            '3.d4 challenges the center at once.',
            '3...Bg4 pins the knight.',
            '4.dxe5 opens the position.',
            '4...Bxf3 gives up the bishop pair to avoid losing a pawn.',
            '5.Qxf3 recaptures, and the queen is now active.',
            '5...dxe5.',
            '6.Bc4 develops with a threat: Qxf7#.',
            '6...Nf6 blocks the queen.',
            '7.Qb3! hits f7 and b7 at the same time.',
            '7...Qe7 defends f7, but the queen blocks the f8-bishop.',
            '8.Nc3 develops instead of grabbing b7.',
            '8...c6 protects b7 with a pawn.',
            '9.Bg5 pins the knight to the queen. White has four pieces out; Black has two.',
            '9...b5? attacks the bishop and opens the queenside. What would Morphy do?',
          ],
        },
        {
          kind: 'move',
          title: 'Open the lines',
          text: 'Black\'s king is still in the center and his pieces are undeveloped. Keep the initiative: do not retreat the bishop.',
          fen: 'rn2kb1r/p3qppp/2p2n2/1p2p1B1/2B1P3/1QN5/PPP2PPP/R3K2R w KQkq - 0 10',
          solution: ['Nxb5', 'cxb5', 'Bxb5+'],
          hint: 'A piece sacrifice on b5 rips open the diagonal to e8.',
          success: '10.Nxb5! cxb5 11.Bxb5+ and White\'s pieces pour in. Morphy gave a knight to open lines against the uncastled king.',
        },
        {
          kind: 'demo',
          title: 'The finish',
          text: 'Morphy brings his last pieces into the attack with gain of time.',
          fen: 'rn2kb1r/p3qppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/R3K2R b KQkq - 0 11',
          moves: ['Nbd7', 'O-O-O', 'Rd8', 'Rxd7', 'Rxd7', 'Rd1', 'Qe6', 'Bxd7+', 'Nxd7'],
          notes: [
            '11...Nbd7 blocks the check.',
            '12.O-O-O! castles and brings the rook to the open d-file at once.',
            '12...Rd8 defends the pinned knight.',
            '13.Rxd7! Rxd7 14.Rd1 keeps piling up on the pinned rook.',
            '13...Rxd7.',
            '14.Rd1: the last white piece joins the attack.',
            '14...Qe6 unpins the knight on f6 to defend d7.',
            '15.Bxd7+ removes a defender.',
            '15...Nxd7. White to play and finish the game.',
          ],
        },
        {
          kind: 'move',
          title: 'Mate in two',
          text: 'Every white piece is active; Black\'s kingside pieces never moved. Find the famous finish: mate in two.',
          fen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
          solution: ['Qb8+', 'Nxb8', 'Rd8#'],
          hint: 'Deflect the knight that guards d8.',
          success: '16.Qb8+!! Nxb8 17.Rd8#. The bishop on g5 covers e7, the rook mates on d8. Black\'s bishop on f8 and rook on h8 never took part.',
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Fight for the center with pawns and pieces.\n- Develop a new piece with almost every move, knights and bishops first.\n- Castle early; do not leave your king in the center.\n- Gain tempi by developing with threats, especially against an early queen.\n- When the opponent\'s king is stuck in the center, open lines even at the cost of material.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'open-common-mistakes',
      title: 'Five Opening Mistakes',
      summary: 'Recognize early queen raids, wasted tempi, greedy pawn grabs and a weakened f-pawn, and learn how to punish them.',
      minutes: 14,
      steps: [
        {
          kind: 'read',
          title: 'Where games are lost early',
          text: 'Most short defeats come from five habits:\n- bringing the queen out early\n- moving the same piece again and again\n- grabbing pawns while behind in development\n- neglecting development altogether\n- weakening the king with an early f-pawn move\n\nEach one costs **tempi** (moves) or loosens the king. When your opponent commits one, look for a way to develop with a threat and open lines.',
        },
        {
          kind: 'read',
          title: 'The early queen raid',
          text: '2.Qh5 attacks e5 and, after Bc4, threatens the Scholar\'s Mate on f7. It is not a good move: the queen can be chased by developing moves, and each chase gives Black a free tempo.\n\nThe answer is not panic but calm development that defends f7 and gains time on the queen.',
          fen: 'rnbqkbnr/pppp1ppp/8/4p2Q/4P3/8/PPPP1PPP/RNB1KBNR b KQkq - 1 2',
          lastMove: ['d1', 'h5'],
          arrows: [
            { from: 'h5', to: 'f7', color: 'red' },
            { from: 'h5', to: 'e5', color: 'red' },
          ],
        },
        {
          kind: 'move',
          title: 'Defend and gain time',
          text: 'After 1.e4 e5 2.Qh5 Nc6 3.Bc4, White threatens Qxf7#. Defend with a move that also attacks the queen, then keep developing.',
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3',
          solution: ['g6', 'Qf3', 'Nf6'],
          hint: 'First kick the queen with a pawn. When she returns to f3, block her path to f7 with a developing move.',
          success: '3...g6 and 4...Nf6 parry both threats while developing. White\'s queen has now moved twice, and Black will soon gain more time with ...Nd4 or ...Bg7 and ...O-O.',
        },
        {
          kind: 'read',
          title: 'Copying and wasting moves',
          text: 'In the Petroff, after 1.e4 e5 2.Nf3 Nf6 3.Nxe5, copying White with 3...Nxe4? is a mistake (3...d6 first is correct).\n\nWhite answers 4.Qe2! The knight on e4 is attacked and sits on the open e-file in front of Black\'s king. The only good reply is 4...Qe7. Moving the knight a third time with 4...Nf6?? loses at once.',
          fen: 'rnbqkb1r/pppp1ppp/8/4N3/4n3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 4',
          lastMove: ['f6', 'e4'],
          arrows: [{ from: 'd1', to: 'e2', color: 'green' }],
        },
        {
          kind: 'move',
          title: 'Punish the wandering knight',
          text: 'Black played 4...Nf6??, moving the knight for the third time. Now the e-file is open between White\'s queen and Black\'s king. Win the queen.',
          fen: 'rnbqkb1r/pppp1ppp/5n2/4N3/8/8/PPPPQPPP/RNB1KB1R w KQkq - 2 5',
          solution: ['Nc6+'],
          hint: 'Move the knight off the e-file with a discovered check, and make it attack something big.',
          success: '5.Nc6+! is a **discovered check** from the queen on e2, and the knight attacks the queen on d8. Black must deal with the check and loses the queen.',
        },
        {
          kind: 'read',
          title: 'The f-pawn weakness',
          text: 'The pawns on f2 and f7 are defended only by the king. Moving the f-pawn early also opens the diagonal from h5 (or h4) to the king.\n\nThe Damiano Defence, 1.e4 e5 2.Nf3 f6?, is the classic example. White can answer 3.Nxe5!, because 3...fxe5? runs into a queen check on the open diagonal. Black\'s best tries are 3...Qe7 or 3...Ne7, and even then White keeps a clear advantage.',
          fen: 'rnbqkbnr/pppp2pp/5p2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3',
          lastMove: ['f7', 'f6'],
          arrows: [
            { from: 'f3', to: 'e5', color: 'green' },
            { from: 'h5', to: 'e8', color: 'red' },
          ],
        },
        {
          kind: 'move',
          title: 'Exploit the open diagonal',
          text: 'After 3.Nxe5 fxe5? Black is a knight up for a pawn. Show why the f-pawn move was a disaster.',
          fen: 'rnbqkbnr/pppp2pp/8/4p3/4P3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 4',
          solution: ['Qh5+', 'g6', 'Qxe5+'],
          hint: 'Check the king along the e8-h5 diagonal first.',
          success: '4.Qh5+ g6 5.Qxe5+ forks king and rook, and White wins the rook on h8. After 4...Ke7 instead, 5.Qxe5+ Kf7 6.Bc4+ starts a king hunt.',
        },
        {
          kind: 'read',
          title: 'Grabbing pawns',
          text: 'Winning a pawn is good; holding on to it at any cost is not. In the Queen\'s Gambit Accepted, 1.d4 d5 2.c4 dxc4 3.e3, Black tried to keep the extra pawn with 3...b5? 4.a4 c6 5.axb5 cxb5?.\n\nBlack has made five pawn moves and developed nothing. Look at the long light diagonal from f3 to a8.',
          fen: 'rnbqkbnr/p3pppp/8/1p6/2pP4/4P3/1P3PPP/RNBQKBNR w KQkq - 0 6',
          lastMove: ['c6', 'b5'],
          marks: [{ square: 'a8', color: 'red' }],
        },
        {
          kind: 'move',
          title: 'Hit the loose rook',
          text: 'White to move. Use the open diagonal to punish Black\'s pawn grabbing.',
          fen: 'rnbqkbnr/p3pppp/8/1p6/2pP4/4P3/1P3PPP/RNBQKBNR w KQkq - 0 6',
          solution: ['Qf3', 'Nc6', 'Qxc6+'],
          hint: 'The queen can attack a8 from f3, where nothing stands in the way.',
          success: '6.Qf3! attacks the rook. 6...Nc6 blocks, but 7.Qxc6+ wins a whole piece. Black\'s undeveloped queenside could not hold.',
        },
        {
          kind: 'quiz',
          title: 'When moving twice is fine',
          text: 'After 1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5, White moves the knight a second time. Why is this playable?',
          fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p1N1/2B1P3/8/PPPP1PPP/RNBQK2R b KQkq - 5 4',
          arrows: [
            { from: 'g5', to: 'f7', color: 'red' },
            { from: 'c4', to: 'f7', color: 'red' },
          ],
          choices: [
            {
              text: 'It creates a concrete threat against f7 that Black must answer at once.',
              correct: true,
              why: 'Knight and bishop both hit f7. A second move with the same piece is justified when it forces the opponent to react, so Black cannot use the time freely.',
            },
            {
              text: 'Knights should always make two moves in the opening.',
              why: 'No such rule exists. Without a threat, a second knight move just gives the opponent a free tempo.',
            },
            {
              text: 'It prepares queenside castling.',
              why: 'The knight on g5 has nothing to do with queenside castling.',
            },
            {
              text: 'It wins material by force.',
              why: 'Black defends with 4...d5 and fights on. The point is the threat, not a forced win.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Meet an early queen with developing moves that attack her.\n- Move a piece twice only when it creates a threat or wins something.\n- Do not grab or hold pawns while your pieces sit at home.\n- Keep the f-pawn at home early; it guards your king.\n- Against these mistakes, develop with threats and open lines toward the king.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'open-king-traps',
      title: 'Traps Against the King',
      summary: 'Fool\'s Mate, From\'s Gambit, Légal\'s Trap and the Blackburne Shilling: spring them, and never fall for them.',
      minutes: 14,
      steps: [
        {
          kind: 'read',
          title: 'Why learn traps',
          text: 'A **trap** is a position where the natural-looking move loses. Knowing the classics pays twice: you will never fall into them, and you will recognize the patterns behind them in your own games.\n\nNearly every trap in this lesson punishes the same errors: loosening the pawns around the king, grabbing material while behind in development, and moving without asking what the opponent threatens.',
        },
        {
          kind: 'demo',
          title: 'Fool\'s Mate',
          text: 'The fastest possible checkmate. It shows what happens when the f- and g-pawns leave the king.',
          fen: START,
          moves: ['f3', 'e5', 'g4', 'Qh4#'],
          notes: [
            '1.f3? weakens the e1-h4 diagonal and does nothing for development.',
            '1...e5 opens a diagonal for Black\'s queen.',
            '2.g4?? opens the diagonal completely.',
            '2...Qh4#. The king cannot move, and nothing can block or capture the queen.',
          ],
        },
        {
          kind: 'move',
          title: 'The same pattern for White',
          text: 'After 1.e4 f5? 2.exf5 g5?? Black has made the same mistake with colors reversed. Finish it.',
          fen: 'rnbqkbnr/ppppp2p/8/5Pp1/8/8/PPPP1PPP/RNBQKBNR w KQkq - 0 3',
          solution: ['Qh5#'],
          hint: 'Look at the diagonal from d1 to e8.',
          success: '3.Qh5#. The pawns on f7 and g7 that should guard e8 have both moved.',
        },
        {
          kind: 'move',
          title: 'From\'s Gambit trap',
          text: 'In From\'s Gambit, 1.f4 e5 2.fxe5 d6 3.exd6 Bxd6, Black sacrifices a pawn to open lines against White\'s king. The normal move is 4.Nf3, covering h4. White played 4.Nc3?? instead. Punish it.',
          fen: 'rnbqk1nr/ppp2ppp/3b4/8/8/2N5/PPPPP1PP/R1BQKBNR b KQkq - 1 4',
          solution: ['Qh4+'],
          hint: 'The e1-h4 diagonal is open, and your bishop already aims at g3.',
          success: '4...Qh4+ 5.g3 (forced) Qxg3+ 6.hxg3 Bxg3#. White\'s 1.f4 opened the diagonal, and the knight that should have guarded h4 went to c3.',
        },
        {
          kind: 'demo',
          title: 'Légal\'s Trap',
          text: 'Named after Kermur de Légal, Philidor\'s teacher and the strongest player in Paris in the mid-1700s. Black pins the knight on f3 and assumes it cannot move.',
          fen: START,
          moves: ['e4', 'e5', 'Bc4', 'd6', 'Nf3', 'Bg4', 'Nc3', 'g6'],
          notes: [
            'An open game.',
            '1...e5.',
            '2.Bc4 aims at f7.',
            '2...d6 is solid but passive.',
            '3.Nf3 attacks e5.',
            '3...Bg4 pins the knight to the queen.',
            '4.Nc3 develops.',
            '4...g6? spends a tempo on the kingside. White can now break the pin by force.',
          ],
        },
        {
          kind: 'move',
          title: 'Break the pin',
          text: 'The knight on f3 is pinned to the queen, but only the queen is at stake. Find the move that wins material in every line.',
          fen: 'rn1qkbnr/ppp2p1p/3p2p1/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5',
          solution: ['Nxe5'],
          hint: 'Ignore the pin and take a pawn.',
          success: '5.Nxe5! If 5...dxe5, 6.Qxg4 and White is a clean pawn up. The greedy 5...Bxd1?? loses to a mate, as you will see next.',
        },
        {
          kind: 'move',
          title: 'Mate in two',
          text: 'Black took the queen with 5...Bxd1??. Now punish the weakened f7-square: mate in two.',
          fen: 'rn1qkbnr/ppp2p1p/3p2p1/4N3/2B1P3/2N5/PPPP1PPP/R1BbK2R w KQkq - 0 6',
          solution: ['Bxf7+', 'Ke7', 'Nd5#'],
          hint: 'Start with a bishop check on f7.',
          success: '6.Bxf7+ Ke7 7.Nd5#. Three minor pieces mate the king. Légal is said to have won this way in Paris around 1750.',
        },
        {
          kind: 'move',
          title: 'Blackburne Shilling Gambit',
          text: 'After 1.e4 e5 2.Nf3 Nc6 3.Bc4 Nd4?! (a dubious move that moves the knight twice), White grabbed the pawn with 4.Nxe5?. Find Black\'s strongest reply.',
          fen: 'r1bqkbnr/pppp1ppp/8/4N3/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4',
          solution: ['Qg5'],
          hint: 'The queen can attack two white targets at once: the knight and a pawn near White\'s king.',
          success: '4...Qg5! hits the knight on e5 and the pawn on g2. White must give material back with 5.O-O or 5.Bxf7+. The natural 5.Nxf7? loses.',
        },
        {
          kind: 'move',
          title: 'Spring the trap',
          text: 'White played 5.Nxf7?, forking the queen and the rook. Ignore the fork.',
          fen: 'r1b1kbnr/pppp1Npp/8/6q1/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 5',
          solution: ['Qxg2'],
          hint: 'Take a pawn with the queen and attack the rook on h1.',
          success: '5...Qxg2! 6.Rf1 Qxe4+ 7.Be2 Nf3# is the famous finish: White\'s own pieces block every escape square. Blackburne is said to have won many a shilling this way.',
        },
        {
          kind: 'quiz',
          title: 'Avoiding the Shilling',
          text: 'White to move after 3...Nd4. Which is the best way to meet it?',
          fen: 'r1bqkbnr/pppp1ppp/8/4p3/2BnP3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
          choices: [
            {
              text: '4.Nxd4',
              correct: true,
              why: 'Trading off the knight that moved twice leaves White ahead in development. After 4...exd4 5.O-O or 5.c3 White is clearly better.',
            },
            {
              text: '4.Nxe5',
              why: 'This grabs a pawn and walks into 4...Qg5!, the whole point of Black\'s gambit.',
            },
            {
              text: '4.Ng5',
              why: 'It attacks f7 but leaves the knight hanging: 4...Qxg5 wins a piece.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Keep the f- and g-pawns home in the opening; they shield the king.\n- A pinned piece may still move if the loss of the piece behind it is repaid with interest.\n- f2 and f7 are the weakest squares early on.\n- Distrust free material in the opening: ask what the opponent gets for it.\n- Before every move, ask what your opponent\'s last move threatens.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'open-material-traps',
      title: 'Traps That Win Material',
      summary: 'The Fishing Pole, Noah\'s Ark, the Elephant Trap and the Lasker Trap: how pieces get trapped and queens get lost.',
      minutes: 14,
      steps: [
        {
          kind: 'read',
          title: 'Traps beyond mate',
          text: 'Not every trap ends in mate. Many win material by **trapping** a piece that has no safe square, or by a **discovered attack** that uncovers a line to the queen or king.\n\nThe traps in this lesson come from the Ruy Lopez and the Queen\'s Gambit, two of the most played openings at every level. You will meet them in your own games.',
        },
        {
          kind: 'demo',
          title: 'The Fishing Pole',
          text: 'In the Ruy Lopez, Black dangles the knight on g4 as bait. If White bites, the h-file opens toward White\'s king.',
          fen: START,
          moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Ng4', 'h3', 'h5', 'hxg4', 'hxg4', 'Ne1', 'Qh4', 'f3', 'g3'],
          notes: [
            'The Ruy Lopez.',
            '1...e5.',
            '2.Nf3.',
            '2...Nc6.',
            '3.Bb5 pressures the defender of e5.',
            '3...Nf6, the Berlin Defence.',
            '4.O-O.',
            '4...Ng4?! is the bait. It is not a good move against careful play.',
            '5.h3 asks the knight to leave.',
            '5...h5! The knight stays. Taking it opens the h-file.',
            '6.hxg4? bites.',
            '6...hxg4 attacks the knight on f3, and the rook on h8 already eyes h1.',
            '7.Ne1 saves the knight.',
            '7...Qh4 threatens ...Qh2# and ...Qh1#.',
            '8.f3 gives the king f2.',
            '8...g3! and ...Qh2# cannot be stopped.',
          ],
        },
        {
          kind: 'move',
          title: 'Reel it in',
          text: 'Same trap, different try: after 6.hxg4 hxg4 White grabbed a pawn with 7.Nxe5?. Find the move that starts a mating attack.',
          fen: 'r1bqkb1r/pppp1pp1/2n5/1B2N3/4P1p1/8/PPPP1PP1/RNBQ1RK1 b kq - 0 7',
          solution: ['Qh4'],
          hint: 'Bring the queen to the open h-file.',
          success: '7...Qh4! threatens ...Qh2# and ...Qh1#. After 8.f4 g3 the mate on the h-file cannot be stopped for long.',
        },
        {
          kind: 'quiz',
          title: 'Avoiding the Fishing Pole',
          text: 'After 5...h5, how should White react?',
          fen: 'r1bqkb1r/pppp1pp1/2n5/1B2p2p/4P1n1/5N1P/PPPP1PP1/RNBQ1RK1 w kq - 0 6',
          choices: [
            {
              text: 'Ignore the knight and play in the center with 6.d4 or 6.c3.',
              correct: true,
              why: 'The knight on g4 does no harm. White develops and strikes in the center, and Black\'s ...h5 has only weakened his own king. White is clearly better.',
            },
            {
              text: 'Win the knight with 6.hxg4.',
              why: 'This opens the h-file for Black\'s rook and queen, and White gets mated or loses heavily.',
            },
            {
              text: 'Trade it with 6.Nh2.',
              why: 'After 6...Nxh2 7.Kxh2 Black follows with ...g5 and ...g4, and Black has the easier game.',
            },
          ],
        },
        {
          kind: 'demo',
          title: 'Noah\'s Ark Trap',
          text: 'In the Ruy Lopez, the bishop that retreats to b3 can be locked in by Black\'s queenside pawns. The name jokes that the trap is as old as Noah\'s Ark.',
          fen: START,
          moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'd6', 'd4', 'b5', 'Bb3', 'Nxd4', 'Nxd4', 'exd4'],
          notes: [
            'The Ruy Lopez.',
            '1...e5.',
            '2.Nf3.',
            '2...Nc6.',
            '3.Bb5.',
            '3...a6 asks the bishop a question.',
            '4.Ba4.',
            '4...d6, the Steinitz Deferred.',
            '5.d4 strikes in the center.',
            '5...b5 gains space and drives the bishop back.',
            '6.Bb3. The bishop is now only defended by pawns.',
            '6...Nxd4 trades a pair of knights.',
            '7.Nxd4.',
            '7...exd4. Recapturing with the queen looks natural. It is a blunder.',
          ],
        },
        {
          kind: 'move',
          title: 'Build the ark',
          text: 'White played 8.Qxd4??. Start the plan that traps the bishop on b3.',
          fen: 'r1bqkbnr/2p2ppp/p2p4/1p6/3QP3/1B6/PPP2PPP/RNB1K2R b KQkq - 0 8',
          solution: ['c5', 'Qd5', 'Be6'],
          hint: 'Kick the queen with a pawn that will later attack the bishop.',
          success: '8...c5! 9.Qd5 Be6 10.Qc6+ Bd7 11.Qd5 c4, and the bishop is trapped. White should have played 8.c3 or 8.Bd5 instead of taking with the queen.',
        },
        {
          kind: 'read',
          title: 'The Elephant Trap',
          text: 'In the Queen\'s Gambit Declined, after 1.d4 d5 2.c4 e6 3.Nc3 Nf6 4.Bg5 Nbd7 5.cxd5 exd5, the knight on f6 seems pinned to the queen. So 6.Nxd5?? looks like it wins a pawn.\n\nIt does not. The "pin" is an illusion, because Black can give up the queen and win it back with a check.',
          fen: 'r1bqkb1r/pppn1ppp/5n2/3p2B1/3P4/2N5/PP2PPPP/R2QKBNR w KQkq - 0 6',
          arrows: [
            { from: 'g5', to: 'd8', color: 'blue' },
            { from: 'c3', to: 'd5', color: 'red' },
          ],
        },
        {
          kind: 'move',
          title: 'Spring the Elephant Trap',
          text: 'White played 6.Nxd5??. Win a piece.',
          fen: 'r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6',
          solution: ['Nxd5', 'Bxd8', 'Bb4+'],
          hint: 'Take the knight and let White take your queen. Then check.',
          success: '6...Nxd5! 7.Bxd8 Bb4+ 8.Qd2 Bxd2+ 9.Kxd2 Kxd8, and Black is a piece up. If White does not take the queen, Black simply keeps the extra knight.',
        },
        {
          kind: 'move',
          title: 'The Lasker Trap',
          text: 'In the Albin Countergambit, 1.d4 d5 2.c4 e5 3.dxe5 d4 4.e3? Bb4+ 5.Bd2 dxe3 6.Bxb4?? walks into one of the most famous tricks in chess. Find it.',
          fen: 'rnbqk1nr/ppp2ppp/8/4P3/1BP5/4p3/PP3PPP/RN1QKBNR b KQkq - 0 6',
          solution: ['exf2+', 'Ke2', 'fxg1=N+'],
          hint: 'Capture with check, uncovering an attack on White\'s queen. On the next move, promote to the piece that gives check.',
          success: '6...exf2+ 7.Ke2 (7.Kxf2 Qxd1) fxg1=N+! A knight promotion with check. After 8.Rxg1 Bg4+ Black wins the queen; 8.Ke1 Qh4+ leaves White\'s king defenceless.',
        },
        {
          kind: 'quiz',
          title: 'The common thread',
          text: 'Which habit would have saved White in every trap in this lesson?',
          choices: [
            {
              text: 'Asking "what does my opponent get if I take?" before grabbing material.',
              correct: true,
              why: 'In each trap White grabbed something (a knight, a pawn, a bishop) without checking the opponent\'s forcing replies: checks, captures and threats.',
            },
            {
              text: 'Never capturing anything in the opening.',
              why: 'Many captures are good. The skill is to check the consequences, not to avoid captures.',
            },
            {
              text: 'Always keeping the queen on d1.',
              why: 'The queen was lost in some traps, but the cause was greed and a missed tactic, not the queen\'s position.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- Before taking material, list your opponent\'s checks, captures and threats in reply.\n- A pin against the queen is not absolute: the queen can be sacrificed if it is won back.\n- A retreated bishop defended only by pawns can be trapped by a pawn chain.\n- An opened h-file with queen and rook behind it is deadly.\n- Discovered attacks and underpromotions win games at every level.',
        },
      ],
    },

    // ---------------------------------------------------------------------------------------------
    {
      id: 'open-to-middlegame',
      title: 'From Opening to Middlegame',
      summary: 'Finish development by connecting your rooks, then let the pawn structure tell you where to play.',
      minutes: 14,
      steps: [
        {
          kind: 'read',
          title: 'When is the opening over?',
          text: 'The opening is finished when three things are true:\n- all minor pieces are developed\n- the king is castled\n- the rooks are **connected**: nothing stands between them on the back rank\n\nAt that point stop playing by rules of thumb and start looking for a **plan**. The best guide to the right plan is the pawn structure.',
        },
        {
          kind: 'quiz',
          title: 'Connecting the rooks',
          text: 'In this Italian Game position, what still separates White\'s rooks on a1 and e1?',
          fen: 'r1bqr1k1/bpp2pp1/p1np1n1p/4p3/4P3/1BPP1N1P/PP1N1PP1/R1BQR1K1 w - - 2 11',
          choices: [
            {
              text: 'The bishop on c1 and the queen on d1.',
              correct: true,
              why: 'Both still sit on the back rank. A typical way to finish development is Nf1-g3, then Be3 and Qe2 or Qc2, after which the rooks see each other.',
            },
            {
              text: 'The knight on d2.',
              why: 'The knight is on the second rank; it does not block the back rank, though it does block the c1-bishop.',
            },
            {
              text: 'The king on g1.',
              why: 'The king stands beyond the e1-rook, not between the rooks.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'Pawns tell you the plan',
          text: 'Pawns move slowly and never move back, so the pawn structure changes less than anything else on the board. Typical guides:\n- **Locked center**: play on the wing where your pawns point, and attack the base of the enemy chain.\n- **Open center**: develop fast, put rooks on open files, watch king safety.\n- **Isolated d-pawn**: its owner wants active pieces and an attack; the opponent wants trades and a blockade.\n- **Queenside majority**: create a passed pawn, often in the endgame.',
        },
        {
          kind: 'demo',
          title: 'Attack the base of the chain',
          text: 'In the French Advance the center is locked. White\'s chain d4-e5 points to the kingside, Black\'s chain d5-e6 points to the queenside. Black attacks the base of White\'s chain, the pawn on d4.',
          fen: START,
          moves: ['e4', 'e6', 'd4', 'd5', 'e5', 'c5', 'c3', 'Nc6', 'Nf3', 'Qb6'],
          notes: [
            '1.e4.',
            '1...e6, the French Defence.',
            '2.d4.',
            '2...d5 challenges e4.',
            '3.e5 gains space and locks the center.',
            '3...c5! strikes at d4, the base of White\'s chain.',
            '4.c3 supports d4 with another pawn.',
            '4...Nc6 adds a second attacker.',
            '5.Nf3 adds a defender.',
            '5...Qb6: a third attacker on d4, and the queen also eyes b2. Later ...Nge7-f5 adds a fourth.',
          ],
        },
        {
          kind: 'move',
          title: 'Prepare before you grab',
          text: 'After 6.Bd3 cxd4 7.cxd4 Black has three pieces attacking d4. Taking it at once is a mistake. Play the quiet move that makes the pawn grab safe.',
          fen: 'r1b1kbnr/pp3ppp/1qn1p3/3pP3/3P4/3B1N2/PP3PPP/RNBQK2R b KQkq - 0 7',
          solution: ['Bd7'],
          hint: 'Which square could a white bishop use to check your king? Cover it.',
          success: '7...Bd7! covers b5. Now 8.O-O Nxd4 9.Nxd4 Qxd4 wins a pawn, and White must look for compensation: this is the Milner-Barry Gambit.',
        },
        {
          kind: 'move',
          title: 'Punish the early grab',
          text: 'Here Black grabbed at once: 7...Nxd4? 8.Nxd4 Qxd4??. Find White\'s winning reply.',
          fen: 'r1b1kbnr/pp3ppp/4p3/3pP3/3q4/3B4/PP3PPP/RNBQK2R w KQkq - 0 9',
          solution: ['Bb5+'],
          hint: 'Move the bishop with check and uncover the d-file.',
          success: '9.Bb5+! checks the king and uncovers the queen on d1 against the queen on d4. After Black deals with the check, 10.Qxd4 wins the queen.',
        },
        {
          kind: 'quiz',
          title: 'Where to play?',
          text: 'A King\'s Indian Defence. The center is locked: White has pawns on d5 and e4, Black on d6 and e5. Black to move. Which plan fits the structure?',
          fen: 'r1bq1rk1/pppnnpbp/3p2p1/3Pp3/2P1P3/2N1B3/PP2BPPP/R2QNRK1 b - - 4 10',
          arrows: [{ from: 'f7', to: 'f5', color: 'green' }],
          choices: [
            {
              text: '...f5, attacking on the kingside where Black\'s pawn chain points.',
              correct: true,
              why: 'Black\'s chain d6-e5 points at the kingside. ...f5 attacks the base of White\'s chain (e4) and prepares ...f4 and ...g5. White plays the mirror plan on the queenside with c5.',
            },
            {
              text: '...c6 and ...b5, attacking on the queenside.',
              why: 'White has more space there, and White\'s chain points that way. Black would be fighting on White\'s strong side.',
            },
            {
              text: 'Keep waiting with moves like ...h6 and ...a6.',
              why: 'In locked positions the side without a plan gets crushed on the wing where the opponent has one.',
            },
          ],
        },
        {
          kind: 'read',
          title: 'The minority attack',
          text: 'In the Queen\'s Gambit Exchange Variation the center is fixed: White has pawns on d4 and e3, Black on d5 and c6. White\'s plan is the **minority attack**: push b4-b5 with two queenside pawns against Black\'s three. After b5xc6, Black is left with a weak pawn on c6 or d5 that White\'s rooks and knights can attack.',
          fen: 'r1bqrnk1/pp2bppp/2p2n2/3p2B1/3P4/2NBPN2/PPQ2PPP/1R3RK1 b - - 9 11',
          arrows: [
            { from: 'b2', to: 'b4', color: 'green' },
            { from: 'b4', to: 'b5', color: 'green' },
          ],
          marks: [{ square: 'c6', color: 'red' }],
        },
        {
          kind: 'quiz',
          title: 'The isolated d-pawn',
          text: 'In this Caro-Kann Panov position White has an **isolated d-pawn**: no pawns on the c- or e-files can defend it. What is White\'s best general plan?',
          fen: 'r1bq1rk1/pp2bppp/2n1p3/3n4/3P4/2NB1N2/PP3PPP/R1BQR1K1 b - - 5 10',
          marks: [{ square: 'd4', color: 'yellow' }],
          choices: [
            {
              text: 'Keep pieces on the board, use the open lines for a kingside attack, and look for the d4-d5 break.',
              correct: true,
              why: 'The isolated pawn gives White space and open files for the pieces. Its weakness shows in the endgame, so White wants action while the pieces are on.',
            },
            {
              text: 'Trade as many pieces as possible.',
              why: 'Every trade brings White closer to an endgame where d4 is a lasting weakness. That is Black\'s plan, not White\'s.',
            },
            {
              text: 'Push the queenside pawns.',
              why: 'Nothing on the queenside justifies it. The action is in the center and on the kingside.',
            },
          ],
        },
        {
          kind: 'move',
          title: 'The d4-d5 break',
          text: 'Another isolated-pawn position. White\'s pieces are all in play: rooks on c1 and d1, the b3-bishop aimed at f7, the g5-bishop pinning the knight. Time to cash in with the typical break.',
          fen: '2rr2k1/1bq1bppp/p1n1pn2/1p4B1/3P4/PBN2N2/1P2QPPP/2RR2K1 w - - 0 1',
          solution: ['d5', 'exd5', 'Nxd5'],
          hint: 'Push the isolated pawn and recapture toward the center.',
          success: 'd5! exd5 Nxd5 opens the d-file and the b3-f7 diagonal. After ...Nxd5 Bxd5, the knight on c6 is pinned against the queen and f7 is under fire. Advancing the isolated pawn at the right moment turns its weakness into activity.',
        },
        {
          kind: 'read',
          title: 'Key takeaways',
          text: '- The opening ends when minor pieces are out, the king is castled and the rooks are connected.\n- Then choose a plan from the pawn structure, not from habit.\n- With a locked center, attack on the side your pawns point to, starting with the base of the enemy chain.\n- Prepare pawn grabs: check for bishop checks and discovered attacks first.\n- Isolated pawn: play for activity. Against it: trade pieces and blockade.',
        },
      ],
    },
  ],
};
